import { leftShadows } from "../../shadow";
import { T } from "../../theme";

export const activationStyles = {
  activationPage: {
    gap: 28,
    paddingBottom: 12,
  },
  activationTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 14,
  },
  activationTopRowTitleWrap: {
    flex: 1,
    minWidth: 0,
    paddingTop: 2,
    gap: 4,
  },
  activationTitle: {
    color: T.textPrimary,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.8,
    textAlign: "left",
  },
  activationSubtitle: {
    color: T.textSecondary,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: T.fontBody,
  },
  activationVenueCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.surfaceGlassStrong,
    paddingHorizontal: 18,
    paddingVertical: 18,
    ...leftShadows.small,
  },
  activationVenueCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  activationVenueIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationVenueCopy: {
    flex: 1,
    gap: 5,
  },
  activationVenueName: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 25,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
  activationVenueBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  activationVenueMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  activationVenueConfidence: {
    color: T.visibilityOff,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyBold,
  },
  activationVenueConfidenceConfirmed: {
    color: T.visibilityOn,
  },
  activationVenueMetaDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: T.visibilityOff,
  },
  activationVenueMetaDotConfirmed: {
    backgroundColor: T.visibilityOn,
  },
  activationVenuePrivacy: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationVenueStatus: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.visibilityOff,
  },
  activationVenueStatusConfirmed: {
    backgroundColor: T.visibilityOn,
  },
  activationChoiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  activationDurationRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  activationHintCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.surfaceGlassStrong,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    ...leftShadows.small,
  },
  activationHintIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationHintContent: {
    flex: 1,
    gap: 2,
  },
  activationHintTitle: {
    color: T.textPrimary,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  activationHintOptional: {
    color: T.textSecondary,
    fontFamily: T.fontBody,
  },
  activationHintEditor: {
    marginTop: -18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 6,
  },
  activationHintInput: {
    color: T.textPrimary,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: T.fontBodyMedium,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  activationHintMeta: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationHintCounter: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBody,
    textAlign: "right",
  },
  activationWarningText: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  activationPrivacyNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 8,
  },
  activationPrivacyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationPrivacyCopy: {
    flex: 1,
    gap: 2,
  },
  activationPrivacyTitle: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  activationPrivacyText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveHero: {
    alignItems: "center",
    gap: 12,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.venueSurface,
    paddingVertical: 28,
    ...leftShadows.small,
  },
  activationLiveStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activationLiveStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: T.visibilityOn,
  },
  activationLiveStatusText: {
    color: T.visibilityOn,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  activationLiveTimer: {
    width: 148,
    height: 148,
    borderRadius: 74,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.venueAccentSoft,
  },
  activationLiveTimerValue: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1.2,
  },
  activationLiveTimerLabel: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationLiveElapsed: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveVenueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    padding: 16,
  },
  activationLiveVenueCopy: {
    flex: 1,
    gap: 2,
  },
  activationLiveVenueLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveSummary: {
    flexDirection: "row",
    alignItems: "stretch",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    paddingVertical: 18,
  },
  activationLiveSummaryItem: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
  },
  activationLiveSummaryDivider: {
    width: 1,
    backgroundColor: T.border,
  },
  activationLiveSummaryLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveSummaryValue: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
    textAlign: "center",
  },
  activationLiveHint: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    borderRadius: 20,
    backgroundColor: T.surfaceMid,
    padding: 16,
  },
  activationLiveHintCopy: {
    flex: 1,
    gap: 2,
  },
  activationLiveHintLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveHintText: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBody,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
} as const;
