import { T } from "../../theme";

export const activationStyles = {
  activationHeader: {
    gap: 6,
    alignItems: "center",
    marginBottom: 6,
  },
  activationTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 14,
    marginBottom: 2,
  },
  activationTopRowTitleWrap: {
    flex: 1,
    minWidth: 0,
    paddingRight: 52,
  },
  activationTitle: {
    color: T.textPrimary,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.8,
    textAlign: "left",
  },
  activationSubtitle: {
    maxWidth: 330,
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    fontFamily: T.fontBody,
    textAlign: "left",
  },
  activationVenueCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(36,92,74,0.10)",
    backgroundColor: "rgba(255,255,255,0.98)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: "#245C4A",
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  activationVenueCardTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  activationVenueIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(36,92,74,0.06)",
    borderWidth: 1,
    borderColor: "rgba(36,92,74,0.10)",
  },
  activationVenueCopy: {
    flex: 1,
    gap: 3,
  },
  activationVenueEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.7,
    textTransform: "uppercase",
  },
  activationVenueName: {
    color: T.textPrimary,
    fontSize: 24,
    lineHeight: 28,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
  activationVenueBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  activationVenueStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: T.visibilityOff,
    marginTop: 8,
  },
  activationVenueStatusDotConfirmed: {
    backgroundColor: T.visibilityOn,
  },
  activationChoiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  activationDurationRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  activationHintCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(53,102,77,0.12)",
    backgroundColor: "rgba(255,251,245,0.88)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    shadowColor: "#DCCCB3",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  activationHintIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(53,102,77,0.08)",
  },
  activationHintContent: {
    flex: 1,
    gap: 8,
  },
  activationHintInput: {
    color: T.textPrimary,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: T.fontBodyMedium,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  activationHintMeta: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationWarningText: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  activationPrivacyNote: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(53,102,77,0.18)",
    backgroundColor: "rgba(255,251,245,0.78)",
  },
  activationPrivacyDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: T.accent,
  },
  activationPrivacyText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
} as const;
