import { leftShadows } from "../../shadow";
import { T } from "../../theme";

export const activationStyles = {
  activationPage: {
    gap: 18,
    paddingBottom: 12,
  },
  activationSectionCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  activationSectionTitle: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 24,
    fontFamily: T.fontBodyBold,
    letterSpacing: -0.2,
  },
  activationSectionDivider: {
    height: 1,
    backgroundColor: T.border,
    marginVertical: 2,
  },
  activationVenueCard: {
    gap: 12,
  },
  activationVenueCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  activationVenueIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationVenueCopy: {
    flex: 1,
    gap: 5,
  },
  activationVenueName: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
  activationVenueBody: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationVenueMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  activationVenueConfidence: {
    color: T.visibilityOff,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
  },
  activationVenueConfidenceConfirmed: {
    color: T.visibilityOn,
  },
  activationVenueMetaDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: T.visibilityOff,
  },
  activationVenueMetaDotConfirmed: {
    backgroundColor: T.visibilityOn,
  },
  activationVenuePrivacy: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBody,
  },
  activationVenueStatus: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.visibilityOff,
  },
  activationVenueStatusConfirmed: {
    backgroundColor: T.visibilityOn,
  },
  activationChoiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  activationDurationRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  activationHintCard: {
    minHeight: 54,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  activationHintIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationHintContent: {
    flex: 1,
    gap: 2,
  },
  activationHintTitle: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  activationHintOptional: {
    color: T.textSecondary,
    fontFamily: T.fontBody,
  },
  activationHintEditor: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 6,
  },
  activationHintInput: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  activationHintMeta: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBody,
  },
  activationHintCounter: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBody,
    textAlign: "right",
  },
  activationWarningText: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  activationPrivacyNote: {
    minHeight: 68,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.025,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  activationPrivacyIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  activationPrivacyCopy: {
    flex: 1,
    gap: 2,
  },
  activationPrivacyTitle: {
    color: T.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyBold,
  },
  activationPrivacyText: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveHero: {
    alignItems: "center",
    gap: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    paddingVertical: 16,
    ...leftShadows.small,
  },
  activationLivePage: {
    gap: 12,
    paddingBottom: 18,
  },
  activationLiveStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activationLiveStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: T.visibilityOn,
  },
  activationLiveStatusText: {
    color: T.visibilityOn,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  activationLiveTimerRing: {
    width: 184,
    height: 184,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  activationLiveTimerSvg: {
    position: "absolute",
    left: 0,
    top: 0,
  },
  activationLiveTimerContent: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  activationLiveTimerValue: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1.2,
  },
  activationLiveTimerLabel: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  activationLiveElapsed: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveVenueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  activationLiveVenueIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  activationLiveVenueName: {
    fontSize: 18,
    lineHeight: 22,
  },
  activationLiveVenueCopy: {
    flex: 1,
    gap: 2,
  },
  activationLiveVenueLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveSummary: {
    flexDirection: "row",
    alignItems: "stretch",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingVertical: 12,
  },
  activationLiveSummaryItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
  },
  activationLiveSummaryIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.surfaceMid,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  activationLiveSummaryCopy: {
    flex: 1,
    gap: 2,
  },
  activationLiveSummaryDivider: {
    width: 1,
    backgroundColor: T.border,
  },
  activationLiveSummaryLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveSummaryValue: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
    textAlign: "left",
  },
  activationLiveHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  activationLiveHintCopy: {
    flex: 1,
    gap: 2,
  },
  activationLiveHintLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  activationLiveHintText: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBody,
  },
  activationLivePrivacyNote: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  activationLivePrivacyIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: T.surfaceMid,
    alignItems: "center",
    justifyContent: "center",
  },
  activationLivePrivacyText: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
} as const;
