import { Platform } from "react-native";
import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const authStyles = {
  authWrap: {
    position: "relative",
    overflow: "hidden",
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 28,
    backgroundColor: T.surface,
  },
  authAmbientLayer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  authAmbientOrb: {
    position: "absolute",
    borderRadius: 999,
    borderWidth: 1,
  },
  authAmbientOrbOne: {
    width: 330,
    height: 330,
    top: -148,
    right: -118,
    borderColor: "rgba(188,218,113,0.20)",
    backgroundColor: "rgba(204,234,132,0.14)",
  },
  authAmbientOrbTwo: {
    width: 260,
    height: 260,
    left: -172,
    bottom: 52,
    borderColor: "rgba(204,185,151,0.16)",
    backgroundColor: "rgba(220,199,158,0.10)",
  },
  authStage: {
    flex: 1,
  },
  authFlowHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  authBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceDim,
  },
  authStepBadge: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: T.surfaceDim,
  },
  authStepDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.onboardingAccent,
  },
  authStepBadgeText: {
    color: T.onboardingInk,
    fontSize: 10,
    letterSpacing: 0.8,
    fontFamily: T.fontBodyBold,
  },
  authHeaderSpacer: {
    width: 44,
    height: 44,
  },
  authBrand: {
    alignItems: "center",
    gap: 8,
    zIndex: 2,
  },
  authWordmark: {
    color: T.onboardingInk,
    fontSize: 12,
    letterSpacing: 3.4,
    fontFamily: T.fontBodyBold,
  },
  authMarkRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
    ...leftShadows.small,
  },
  authCardGlass: {
    marginTop: 20,
  },
  authCard: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    alignItems: "center",
  },
  authEyebrow: {
    color: T.onboardingInkMuted,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 2.8,
    fontFamily: T.fontBodyBold,
    marginBottom: 12,
  },
  authHeadline: {
    color: T.onboardingInk,
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1.6,
    textAlign: "center",
    fontFamily: Platform.select({ ios: "Georgia", default: T.fontDisplayLight }),
  },
  authSub: {
    color: T.onboardingInkSoft,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    fontFamily: T.fontBody,
    maxWidth: 290,
    marginTop: 12,
    marginBottom: 18,
  },
  authBenefitList: {
    width: "100%",
    paddingHorizontal: 14,
    marginBottom: 22,
    borderRadius: 22,
    backgroundColor: T.surfaceDim,
  },
  authBenefitRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authBenefitDivider: {
    borderBottomWidth: 1,
    borderBottomColor: T.onboardingBorder,
  },
  authBenefitIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceCard,
  },
  authBenefitCopy: {
    flex: 1,
    gap: 2,
  },
  authBenefitTitle: {
    color: T.onboardingInk,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBodyBold,
  },
  authBenefitBody: {
    color: T.onboardingInkSoft,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBody,
  },
  authGoogleButton: {
    width: "100%",
    minHeight: 54,
    borderRadius: 17,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
    transform: [{ translateY: -2 }],
    shadowColor: T.onboardingInk,
    shadowOpacity: 0.16,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 9 },
    elevation: 7,
  },
  authButtonDisabled: {
    opacity: 0.62,
  },
  authBtnPressed: {
    opacity: 0.9,
    transform: [{ translateY: 0 }, { scale: 0.99 }],
  },
  authGoogleIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: T.white,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  authGoogleLoading: {
    width: 42,
    height: 42,
    marginVertical: -5,
    alignItems: "center",
    justifyContent: "center",
  },
  authGoogleLabel: {
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  authDividerRow: {
    width: "100%",
    marginVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  authDivider: {
    flex: 1,
    height: 1,
    backgroundColor: T.onboardingBorder,
  },
  authDividerLabel: {
    color: T.onboardingInkMuted,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  authEmailButton: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
  },
  authEmailLabel: {
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  authEmailComingSoon: {
    color: T.onboardingInkMuted,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: T.fontBodyBold,
    textAlign: "center",
    marginTop: 3,
  },
  authPrivacyRow: {
    marginTop: 18,
    marginHorizontal: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  authMemberNote: {
    marginTop: 15,
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    fontFamily: T.fontBodyMedium,
  },
  authPrivacyIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.onboardingAccentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  authPrivacyCopy: {
    flex: 1,
    gap: 4,
  },
  authPrivacyTitle: {
    color: T.onboardingInk,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  authPrivacyBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  errorText: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 16,
    textAlign: "center",
    fontFamily: T.fontBodyMedium,
  },
  authLegalRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  authLegalLink: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textDecorationLine: "underline",
    fontFamily: T.fontBodyMedium,
  },
  authLegalSeparator: {
    color: T.textMuted,
    fontSize: 12,
  },
} as const;
