import { T } from "../../theme";

export const authStyles = {
  authWrap: {
    flex: 1,
    minHeight: 812,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  authGlowTop: {
    position: "absolute",
    top: -120,
    left: "15%",
    right: "15%",
    height: 400,
    borderRadius: 200,
    backgroundColor: "rgba(255,195,77,0.10)",
  },
  authGlowBottom: {
    position: "absolute",
    bottom: -80,
    left: "10%",
    right: "10%",
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(53,102,77,0.08)",
  },
  authBrand: {
    alignItems: "center",
    paddingTop: 100,
    gap: 12,
  },
  authMarkRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: "rgba(53,102,77,0.16)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,251,245,0.88)",
  },
  authMarkChevron: {
    color: T.accentBright,
    fontSize: 34,
    fontWeight: "200",
    lineHeight: 40,
    marginRight: -4,
  },
  authMarkDot: {
    position: "absolute",
    right: 17,
    top: 24,
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: T.accent,
  },
  authWordmarkWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authWordmarkRule: {
    width: 26,
    height: 1,
    backgroundColor: "rgba(53,102,77,0.22)",
  },
  authWordmark: {
    color: T.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 4.2,
  },
  authCard: {
    marginHorizontal: 20,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.white,
    paddingHorizontal: 26,
    paddingTop: 32,
    paddingBottom: 36,
    overflow: "hidden",
  },
  authCardAccentLine: {
    position: "absolute",
    top: 0,
    left: 40,
    right: 40,
    height: 1,
    backgroundColor: T.secondary,
    opacity: 0.6,
  },
  authHeadline: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "300",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    marginBottom: 14,
    textAlign: "center",
  },
  authSub: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 36,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  authBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.primary,
    borderRadius: 16,
    paddingVertical: 17,
    paddingHorizontal: 20,
  },
  authBtnPressed: {
    opacity: 0.85,
  },
  authBtnGIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(244,200,90,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  authBtnG: {
    color: T.white,
    fontSize: 14,
    fontWeight: "800",
  },
  authBtnLabel: {
    color: T.white,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  authFooter: {
    alignItems: "center",
    paddingBottom: 36,
    gap: 8,
  },
  authFooterLinks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authFooterLink: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterDivider: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterCopy: {
    color: T.textMuted,
    fontSize: 11,
    letterSpacing: 3,
  },
  errorText: {
    color: "#ff8080",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
} as const;
