import { Platform } from "react-native";
import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const authStyles = {
  authWrap: {
    position: "relative",
    overflow: "hidden",
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 28,
    backgroundColor: T.surface,
  },
  authHeroArc: {
    position: "absolute",
    top: -390,
    left: -220,
    right: -220,
    height: 730,
    borderRadius: 365,
    borderWidth: 1,
    borderColor: T.onboardingDecorativeBorder,
  },
  authBrand: {
    alignItems: "center",
    gap: 10,
    zIndex: 2,
  },
  authWordmark: {
    color: T.onboardingInk,
    fontSize: 12,
    letterSpacing: 3.4,
    fontFamily: T.fontBodyBold,
  },
  authMarkRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
    ...leftShadows.small,
  },
  authCardGlass: {
    marginTop: 24,
  },
  authCard: {
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 18,
    alignItems: "center",
  },
  authEyebrow: {
    color: T.onboardingInkMuted,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 2.8,
    fontFamily: T.fontBodyBold,
    marginBottom: 14,
  },
  authHeadline: {
    color: T.onboardingInk,
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1.6,
    textAlign: "center",
    fontFamily: Platform.select({ ios: "Georgia", default: T.fontDisplayLight }),
  },
  authSub: {
    color: T.onboardingInkSoft,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    fontFamily: T.fontBody,
    marginTop: 14,
    marginBottom: 20,
  },
  authGoogleButton: {
    width: "100%",
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: T.actionSurface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
    shadowColor: T.actionSurface,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  authButtonDisabled: {
    opacity: 0.62,
  },
  authBtnPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.995 }],
  },
  authGoogleIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: T.white,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  authGoogleLabel: {
    color: T.onboardingAccent,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  authDividerRow: {
    width: "100%",
    marginVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  authDivider: {
    flex: 1,
    height: 1,
    backgroundColor: T.onboardingBorder,
  },
  authDividerLabel: {
    color: T.onboardingInkMuted,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  authEmailButton: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
  },
  authEmailLabel: {
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  authEmailComingSoon: {
    color: T.onboardingInkMuted,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: T.fontBodyBold,
    textAlign: "center",
    marginTop: 3,
  },
  authPrivacyRow: {
    marginTop: 15,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  authPrivacyIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.onboardingAccentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  authPrivacyCopy: {
    flex: 1,
    gap: 4,
  },
  authPrivacyTitle: {
    color: T.onboardingInk,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  authPrivacyBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  errorText: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 16,
    textAlign: "center",
    fontFamily: T.fontBodyMedium,
  },
  authLegalRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  authLegalLink: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textDecorationLine: "underline",
    fontFamily: T.fontBodyMedium,
  },
  authLegalSeparator: {
    color: T.textMuted,
    fontSize: 12,
  },
} as const;
