import { T } from "../../theme";

export const discoveryStyles = {
  discoveryPage: { gap: 22 },
  discoveryList: { gap: 10 },
  discoveryEmptyCard: {
    minHeight: 280,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    borderStyle: "dashed",
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    gap: 11,
  },
  discoveryEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  discoveryEmptyTitle: { color: T.textPrimary, fontSize: 20, lineHeight: 25, fontFamily: T.fontDisplayBold },
  discoveryEmptyText: { color: T.textSecondary, fontSize: 13, lineHeight: 19, fontFamily: T.fontBodyMedium, textAlign: "center" },
  discoveryInlineAction: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 7, marginTop: 6 },
  discoveryInlineActionText: { color: T.primary, fontSize: 13, lineHeight: 17, fontFamily: T.fontBodyBold },
  discoveryVenueRow: {
    minHeight: 84,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 15,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  discoveryVenueIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: T.primarySoft, alignItems: "center", justifyContent: "center" },
  discoveryVenueCopy: { flex: 1, minWidth: 0, gap: 4 },
  discoveryVenueName: { color: T.textPrimary, fontSize: 16, lineHeight: 20, fontFamily: T.fontBodyBold },
  discoveryVenueMeta: { color: T.textSecondary, fontSize: 11, lineHeight: 15, fontFamily: T.fontBodyMedium },
  experienceHero: { gap: 9, borderLeftWidth: 3, borderLeftColor: T.primary, paddingLeft: 15, marginTop: 8 },
  experienceEyebrow: { color: T.primary, fontSize: 9, lineHeight: 12, fontFamily: T.fontBodyBold, letterSpacing: 1 },
  experienceTitle: { color: T.textPrimary, fontSize: 31, lineHeight: 36, fontFamily: T.fontDisplayBold, letterSpacing: -0.65 },
  experienceHeroMeta: { flexDirection: "row", alignItems: "center", gap: 7 },
  experienceHeroMetaText: { color: T.textSecondary, fontSize: 12, lineHeight: 16, fontFamily: T.fontBodyBold },
  experienceDescription: { color: T.textPrimary, fontSize: 15, lineHeight: 24, fontFamily: T.fontBody },
  experienceFacts: { borderRadius: 22, borderWidth: 1, borderColor: T.border, backgroundColor: T.surfaceCard, overflow: "hidden" },
  experienceFact: { minHeight: 74, flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderBottomWidth: 1, borderBottomColor: T.border },
  experienceFactIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: T.primarySoft, alignItems: "center", justifyContent: "center" },
  experienceFactCopy: { flex: 1, minWidth: 0, gap: 3 },
  experienceFactTitle: { color: T.textPrimary, fontSize: 14, lineHeight: 18, fontFamily: T.fontBodyBold },
  experienceFactText: { color: T.textSecondary, fontSize: 11, lineHeight: 16, fontFamily: T.fontBodyMedium },
  experienceSafetyNote: { flexDirection: "row", alignItems: "flex-start", gap: 10, paddingHorizontal: 3 },
  experienceSafetyText: { flex: 1, color: T.textSecondary, fontSize: 11, lineHeight: 17, fontFamily: T.fontBodyMedium },
  experiencePrimaryAction: {
    minHeight: 56,
    borderRadius: 17,
    backgroundColor: T.actionSurface,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    shadowColor: T.actionSurface,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  experiencePrimaryActionSelected: { backgroundColor: T.primary },
  experiencePrimaryActionText: { color: T.actionContent, fontSize: 14, lineHeight: 18, fontFamily: T.fontBodyBold },
  experienceReviewNotice: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.primarySoft,
    padding: 16,
    gap: 6,
  },
  experienceReviewEyebrow: { color: T.primary, fontSize: 10, lineHeight: 13, fontFamily: T.fontBodyBold, letterSpacing: 1.2 },
  experienceReviewText: { color: T.textSecondary, fontSize: 13, lineHeight: 19, fontFamily: T.fontBodyMedium },
  experienceChoiceColumn: { gap: 8, alignItems: "flex-start" },
  experienceFieldError: { color: T.danger, fontSize: 13, lineHeight: 18, fontFamily: T.fontBodyMedium },
  experienceValidationHint: { color: T.textSecondary, fontSize: 12, lineHeight: 17, fontFamily: T.fontBodyMedium, textAlign: "center" },
} as const;
