import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const feedStyles = {
  feedPage: {
    gap: 20,
  },
  feedHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  feedHeadCopy: {
    flex: 1,
    gap: 5,
  },
  feedTitle: {
    color: T.textPrimary,
    fontSize: 30,
    lineHeight: 36,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.8,
  },
  feedSubtitle: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBody,
  },
  feedVenueRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...leftShadows.small,
  },
  feedVenueIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueSurface,
  },
  feedVenueCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  feedHeadVenue: {
    color: T.textPrimary,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  feedCountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  feedCountDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.visibilityOff,
  },
  feedCountDotVisible: {
    backgroundColor: T.visibilityOn,
  },
  feedHeadCount: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBody,
  },
  feedList: {
    gap: 12,
  },
  feedCard: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 24,
    padding: 16,
    gap: 14,
    backgroundColor: T.surfaceCard,
    ...leftShadows.small,
  },
  feedCardPressed: {
    opacity: 0.82,
  },
  feedCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedCardInfo: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  feedCardName: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 22,
    fontFamily: T.fontBodyBold,
  },
  feedCardIntentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  feedCardIntent: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  feedCardTimePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: T.surfaceDim,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  feedCardTime: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  feedCardHintRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
    borderRadius: 16,
    backgroundColor: T.surfaceMid,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  feedCardHint: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBody,
  },
  feedCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  feedVibePill: {
    maxWidth: "58%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: T.venueSurface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  feedVibeText: {
    flexShrink: 1,
    color: T.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  feedProfileAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  feedProfileActionText: {
    color: T.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
  },
  emptyState: {
    alignItems: "center",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 28,
    paddingVertical: 44,
    gap: 10,
  },
  emptyGlyphWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
    marginBottom: 4,
  },
  emptyTitle: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 22,
    fontFamily: T.fontBodyBold,
    textAlign: "center",
  },
  emptyText: {
    maxWidth: 290,
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
} as const;
