import { StyleSheet } from "react-native";
import { T } from "../../theme";

export const homeStyles = {
  homePage: {
    gap: 16,
    paddingTop: 14,
  },
  homeVenueHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 0,
    gap: 8,
  },
  homeBrandLockup: {
    alignItems: "center",
    gap: 1,
    marginTop: 2,
  },
  homeBrandMark: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: T.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.borderBlack,
    shadowColor: T.primary,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  homeBrandLabel: {
    color: T.textMuted,
    fontSize: 7,
    lineHeight: 9,
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.25,
    textTransform: "uppercase",
  },
  homeEditorialIntro: {
    marginTop: 16,
    marginBottom: 4,
    gap: 8,
    paddingLeft: 2,
  },
  homeEditorialEyebrow: {
    color: T.primary,
    fontSize: 10,
    lineHeight: 13,
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.15,
  },
  homeEditorialTitle: {
    flexShrink: 1,
    color: T.textPrimary,
    fontSize: 32,
    lineHeight: 36,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.7,
  },
  homeEditorialSupport: {
    maxWidth: "88%",
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  homePresenceCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 14,
    paddingTop: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  homePresenceCardError: {
    borderColor: T.dangerBorder,
  },
  homePresencePrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingBottom: 12,
  },
  homePresenceCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  homePresenceStateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  homePresenceStateDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.visibilityOn,
  },
  homePresenceStateDotHidden: {
    backgroundColor: T.visibilityOff,
  },
  homePresenceStateDotError: {
    backgroundColor: T.danger,
  },
  homePresenceStateLabel: {
    color: T.textSecondary,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
    letterSpacing: 0.9,
  },
  homePresenceVenue: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.35,
  },
  homePresenceMessage: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontFamily: T.fontBodyMedium,
  },
  homePresenceAction: {
    minWidth: 104,
    minHeight: 46,
    borderRadius: 15,
    backgroundColor: T.actionSurface,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    shadowColor: T.actionSurface,
    shadowOpacity: 0.15,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  homePresenceActionError: {
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    shadowOpacity: 0,
  },
  homePresenceActionText: {
    color: T.actionContent,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: T.fontBodyBold,
  },
  homePresenceActionTextError: {
    color: T.danger,
  },
  homePresencePrivacyRow: {
    minHeight: 38,
    borderTopWidth: 1,
    borderTopColor: T.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  homePresencePrivacyText: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homeEditorialSection: {
    marginTop: 23,
    gap: 12,
  },
  homeEditorialSectionHeader: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 2,
  },
  homeEditorialSectionCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homeEditorialSectionEyebrow: {
    color: T.primary,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
    letterSpacing: 1,
  },
  homeEditorialSectionTitle: {
    color: T.textPrimary,
    fontSize: 23,
    lineHeight: 28,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.45,
  },
  homeEditorialSectionMeta: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeFeaturedPlaceCard: {
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    shadowColor: T.primary,
    shadowOpacity: 0.075,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  homeFeaturedPlaceCardPressed: {
    opacity: 0.94,
    transform: [{ translateY: 2 }],
  },
  homeFeaturedPlaceImageWrap: {
    height: 188,
    backgroundColor: T.surfaceDim,
    overflow: "hidden",
  },
  homeFeaturedPlaceShade: {
    ...StyleSheet.absoluteFillObject,
  },
  homeFeaturedPlaceSignal: {
    position: "absolute",
    left: 14,
    top: 14,
  },
  homeFeaturedPlaceSignalContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  homeFeaturedPlaceSignalDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  homeFeaturedPlaceSignalText: {
    color: T.textPrimary,
    fontSize: 10,
    lineHeight: 13,
    fontFamily: T.fontBodyBold,
  },
  homeFeaturedPlaceBody: {
    minHeight: 80,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  homeFeaturedPlaceCopy: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  homeFeaturedPlaceName: {
    color: T.textPrimary,
    fontSize: 21,
    lineHeight: 25,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
  },
  homeFeaturedPlaceMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  homeFeaturedPlaceMeta: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homeFeaturedPlaceArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.actionSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  homePeopleCount: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontFamily: T.fontBodyBold,
  },
  homePersonCard: {
    minHeight: 116,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.primary,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: T.primary,
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  homePersonCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homePersonNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  homePersonName: {
    color: T.white,
    fontSize: 19,
    lineHeight: 23,
    fontFamily: T.fontDisplayBold,
  },
  homePersonTime: {
    color: T.primarySoft,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
  },
  homePersonIntent: {
    color: T.primarySoft,
    fontSize: 10,
    lineHeight: 13,
    fontFamily: T.fontBodyBold,
    textTransform: "capitalize",
  },
  homePersonHint: {
    marginTop: 3,
    color: T.white,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homePersonArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  homePeopleEmptyCard: {
    minHeight: 94,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  homePeopleEmptyIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  homePeopleEmptyCopy: {
    flex: 1,
    gap: 3,
  },
  homePeopleEmptyTitle: {
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  homePeopleEmptyText: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homePeoplePrivateCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    padding: 16,
    gap: 10,
  },
  homePeoplePrivateIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  homePeoplePrivateCopy: {
    gap: 4,
  },
  homePeoplePrivateTitle: {
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  homePeoplePrivateText: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homePeoplePrivateAction: {
    minHeight: 34,
    borderTopWidth: 1,
    borderTopColor: T.border,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  homePeoplePrivateActionText: {
    color: T.primary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
  },
  homeExperienceCard: {
    minHeight: 126,
    borderRadius: 22,
    borderWidth: 1,
    borderLeftWidth: 5,
    borderColor: T.border,
    borderLeftColor: T.primary,
    backgroundColor: T.surfaceCard,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.045,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  homeExperienceDateBlock: {
    width: 54,
    minHeight: 72,
    borderRightWidth: 1,
    borderRightColor: T.borderBlack,
    justifyContent: "center",
  },
  homeExperienceMonth: {
    color: T.primary,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
    letterSpacing: 0.8,
  },
  homeExperienceDay: {
    color: T.textPrimary,
    fontSize: 32,
    lineHeight: 37,
    fontFamily: T.fontDisplayBold,
  },
  homeExperienceCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  homeExperienceTitle: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 21,
    fontFamily: T.fontDisplayBold,
  },
  homeExperienceMeta: {
    color: T.textSecondary,
    fontSize: 10,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homeExperienceSeats: {
    color: T.primary,
    fontSize: 10,
    lineHeight: 14,
    fontFamily: T.fontBodyBold,
  },
  homeExperienceEmptyCard: {
    minHeight: 108,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    borderStyle: "dashed",
    backgroundColor: T.surfaceCard,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  homeExperienceEmptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  homeExperienceHostLink: {
    alignSelf: "flex-start",
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  homeExperienceHostLinkText: {
    color: T.primary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
  },
  homeHeroHeading: {
    gap: 0,
    marginTop: 8,
    marginBottom: 6,
  },
  homeGreetingInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  homeGreetingInlineName: {
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 18,
    fontFamily: T.fontDisplayBold,
  },
  homeGreetingActivityIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueSurface,
  },
  homeHeroTitleAccent: {
    color: T.textPrimary,
    fontSize: 29,
    lineHeight: 34,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.55,
  },
  homeHeroSupportText: {
    marginTop: 7,
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
    maxWidth: "78%",
  },
  homePresenceIndicatorWrap: {
    position: "absolute",
    right: -5,
    bottom: -5,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  homePresenceIndicatorPulse: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  homePresenceIndicatorPulseVisible: {
    backgroundColor: T.visibilityOnSoft,
  },
  homePresenceIndicatorPulseHidden: {
    backgroundColor: T.visibilityOffSoft,
  },
  homePresenceIndicatorDot: {
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 2,
    borderColor: T.ink,
  },
  homePresenceIndicatorDotVisible: {
    backgroundColor: T.visibilityOn,
  },
  homePresenceIndicatorDotHidden: {
    backgroundColor: T.visibilityOff,
  },
  homeHeroCardV2: {
    borderRadius: 24,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    gap: 10,
  },
  homeHeroCardV2Unified: {
    minHeight: 286,
    borderRadius: 28,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    padding: 10,
    shadowColor: T.primary,
    shadowOpacity: 0.035,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  homeHeroCardV2Visible: {
    borderColor: T.border,
  },
  homeHeroCardV2Hidden: {
    borderColor: T.borderBlack,
  },
  homeHeroCardV2Error: {
    borderColor: T.dangerBorder,
  },
  homeHeroVisibleShell: {
    gap: 9,
  },
  homeHeroVenueArtStacked: {
    width: "100%",
    height: 158,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    overflow: "hidden",
  },
  homeVenueIllustrationImage: {
    width: "100%",
    height: "100%",
  },
  homeHeroVenueArtShade: {
    ...StyleSheet.absoluteFillObject,
  },
  homeHeroImageStatusGlass: {
    position: "absolute",
    top: 12,
    right: 12,
  },
  homeHeroImageStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  homeHeroImageStatusPillVisible: {
    backgroundColor: T.visibilityOnSoft,
    borderColor: T.visibilityOnSoft,
  },
  homeHeroImageStatusPillHidden: {
    backgroundColor: T.visibilityOffSoft,
    borderColor: T.visibilityOffSoft,
  },
  homeHeroImageStatusPillError: {
    backgroundColor: T.dangerDim,
    borderColor: T.dangerBorder,
  },
  homeHeroImageStatusText: {
    color: T.textPrimary,
    fontSize: 10,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
    letterSpacing: 0.35,
  },
  homeHeroPeopleGlass: {
    position: "absolute",
    left: 14,
    bottom: 14,
  },
  homeHeroPeopleOverlay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  homeHeroAvatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  homeHeroAvatarBubble: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,251,245,0.92)",
    borderWidth: 1.5,
    borderColor: "rgba(255,251,245,0.96)",
    alignItems: "center",
    justifyContent: "center",
  },
  homeHeroAvatarBubbleOverlap: {
    marginLeft: -5,
  },
  homeHeroAvatarCountBubble: {
    backgroundColor: "rgba(255,251,245,0.88)",
  },
  homeHeroAvatarLabel: {
    color: T.textPrimary,
    fontSize: 8,
    lineHeight: 9,
    fontFamily: T.fontBodyBold,
  },
  homeHeroAvatarCountText: {
    color: T.textPrimary,
    fontSize: 9,
    lineHeight: 10,
    fontFamily: T.fontBodyBold,
  },
  homeHeroPeopleOverlayText: {
    color: T.textPrimary,
    fontSize: 11,
    lineHeight: 13,
    fontFamily: T.fontBodyMedium,
  },
  homeHeroVisibleInfoStack: {
    gap: 12,
  },
  homeHeroVisibleInfoRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    paddingHorizontal: 6,
    paddingTop: 2,
  },
  homeHeroVisibleInfoCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  homeHeroPresenceEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 0,
  },
  homeHeroPresenceEyebrowDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.visibilityOn,
  },
  homeHeroPresenceEyebrowDotHidden: {
    backgroundColor: T.visibilityOff,
  },
  homeHeroPresenceEyebrowDotError: {
    backgroundColor: T.danger,
  },
  homeHeroPresenceEyebrow: {
    color: T.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
    letterSpacing: 0.9,
  },
  homeHeroPresenceEyebrowHidden: {
    color: T.textPrimary,
  },
  homeHeroPresenceEyebrowError: {
    color: T.dangerText,
  },
  homeHeroVenueNameVisible: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 21,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.35,
    maxWidth: "100%",
  },
  homeHeroStatusLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  homeHeroStatusLineText: {
    color: T.textPrimary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homeHeroCardCopyVisible: {
    color: T.textSecondary,
    fontSize: 10,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
    maxWidth: "100%",
  },
  homeVisibleHeroButtonInline: {
    width: 132,
    minHeight: 62,
    borderRadius: 16,
    backgroundColor: T.actionSurface,
    paddingHorizontal: 13,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 0,
  },
  homeVisibleHeroButtonInlineHidden: {
    backgroundColor: T.actionSurface,
  },
  homeVisibleHeroButtonInlineError: {
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.dangerBorder,
  },
  homeVisibleHeroButtonMark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: T.actionContentSoft,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  homeVisibleHeroButtonTextInline: {
    color: T.actionContent,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
    textAlign: "left",
    flexShrink: 1,
  },
  homeVisibleHeroButtonTextInlineError: {
    color: T.dangerText,
  },
  homeHeroVisibleDivider: {
    height: 1,
    backgroundColor: T.border,
    marginHorizontal: 6,
  },
  homeHeroPrivacyRowVisible: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 7,
    marginHorizontal: 6,
    marginBottom: 2,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.border,
  },
  homeHeroPrivacyIconWrapVisible: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: T.surfaceMid,
    alignItems: "center",
    justifyContent: "center",
  },
  homeHeroPrivacyCopyVisible: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  homeHeroPrivacyLabelVisible: {
    color: T.textPrimary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: T.fontBodyBold,
  },
  homeHeroPrivacyTextVisible: {
    color: T.textSecondary,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyMedium,
  },
  homeExploreHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 26,
    marginBottom: 10,
  },
  homeExploreHeaderCopy: {
    gap: 4,
  },
  homeExploreTitle: {
    color: T.textPrimary,
    fontSize: 23,
    lineHeight: 28,
    fontFamily: T.fontBodyBold,
    letterSpacing: -0.45,
  },
  homeExploreMeta: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  homeExploreSideNote: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
  },
  homeVenueGrid: {
    flexDirection: "column",
    gap: 10,
    marginBottom: 10,
  },
  homeVenueEmptyState: {
    minHeight: 156,
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlass,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  homeVenueEmptyTitle: {
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
    fontFamily: T.fontBodyBold,
  },
  homeVenueEmptyBody: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 280,
    textAlign: "center",
    fontFamily: T.fontBody,
  },
  homeVenueGridSingle: {
    flexDirection: "column",
  },
  homeVenueCard: {
    flex: 1,
    minHeight: 126,
    borderRadius: 22,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 13,
    shadowColor: T.primary,
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  homeVenueCardSingle: {
    flex: 1,
    minHeight: 126,
  },
  homeVenueCardRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  homeVenueThumb: {
    width: 100,
    height: 100,
    borderRadius: 18,
    overflow: "hidden",
    position: "relative",
    flexShrink: 0,
  },
  homeVenueThumbFeatured: {
    borderWidth: 1,
    borderColor: T.borderBlack,
  },
  homeVenueCardBody: {
    flex: 1,
    justifyContent: "space-between",
    gap: 6,
  },
  homeVenueCardTopGroup: {
    gap: 4,
  },
  homeVenueCardName: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
    marginBottom: 0,
    flex: 1,
  },
  homeVenueCardNameFeatured: {
    fontSize: 17,
    lineHeight: 21,
  },
  homeVenueStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingTop: 0,
  },
  homeVenueStatusText: {
    fontSize: 13,
    lineHeight: 17,
    fontFamily: T.fontBodyBold,
  },
  homeVenuePeopleRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  homeVenueSignalIconWrap: {
    minHeight: 20,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  homeVenueSignalBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    marginLeft: 2,
  },
  homeVenueSignalBar: {
    width: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  homeVenueSignalBarActive: {
    backgroundColor: T.primary,
    borderColor: T.primary,
  },
  homeVenueSignalBarInactive: {
    backgroundColor: T.surfaceGlassUltra,
  },
  homeVenueDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  homeVenueDistanceText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeVenueChevronBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceGlassUltra,
    borderWidth: 1,
    borderColor: T.border,
    alignSelf: "center",
  },
  homeSafetyCard: {
    minHeight: 74,
    borderRadius: 22,
    backgroundColor: T.venueSurface,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: T.venueAccent,
    shadowOpacity: 0.035,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  homeSafetyCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  homeSafetyCardIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  homeSafetyCardCopy: {
    flex: 1,
    gap: 1,
  },
  homeSafetyCardTitle: {
    color: T.primary,
    fontSize: 15,
    lineHeight: 18,
    fontFamily: T.fontBodyBold,
  },
  homeSafetyCardSubtitle: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homePrivateMapTexture: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: T.surfaceDim,
  },
} as const;
