import { StyleSheet } from "react-native";
import { T } from "../../theme";

export const homeStyles = {
  homePage: {
    gap: 16,
    paddingTop: 18,
  },
  homeVenueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
    gap: 12,
  },
  homeBrandLockup: {
    alignItems: "center",
    gap: 4,
    marginTop: 0,
  },
  homeBrandMark: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: T.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.borderBlack,
    shadowColor: T.primary,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  homeBrandLabel: {
    color: T.textMuted,
    fontSize: 10,
    lineHeight: 12,
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  homeHeroHeading: {
    gap: 0,
    marginTop: 8,
    marginBottom: 4,
  },
  homeGreetingInline: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    marginBottom: 6,
  },
  homeGreetingInlineName: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 22,
    fontFamily: T.fontDisplayBold,
  },
  homeHeroTitleAccent: {
    color: T.textPrimary,
    fontSize: 34,
    lineHeight: 31,
    fontFamily: T.fontDisplayBold,
  },
  homeHeroTitleBottom: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 35,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1.1,
  },
  homePresenceIndicatorWrap: {
    position: "absolute",
    right: -5,
    bottom: -5,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  homePresenceIndicatorPulse: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  homePresenceIndicatorPulseVisible: {
    backgroundColor: T.visibilityOnSoft,
  },
  homePresenceIndicatorPulseHidden: {
    backgroundColor: T.visibilityOffSoft,
  },
  homePresenceIndicatorDot: {
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 2,
    borderColor: T.ink,
  },
  homePresenceIndicatorDotVisible: {
    backgroundColor: T.visibilityOn,
  },
  homePresenceIndicatorDotHidden: {
    backgroundColor: T.visibilityOff,
  },
  homeHeroCardV2: {
    borderRadius: 24,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    gap: 10,
  },
  homeHeroCardV2Unified: {
    minHeight: 286,
    borderRadius: 40,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    padding: 20,
    shadowColor: T.primary,
    shadowOpacity: 0.035,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  homeHeroCardV2Visible: {
    borderColor: T.border,
  },
  homeHeroCardV2Hidden: {
    borderColor: T.borderBlack,
  },
  homeHeroCardV2Error: {
    borderColor: T.dangerBorder,
  },
  homeHeroVisibleShell: {
    gap: 8,
  },
  homeHeroVenueArtStacked: {
    width: "100%",
    height: 170,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    overflow: "hidden",
  },
  homeVenueIllustrationImage: {
    width: "100%",
    height: "100%",
  },
  homeHeroVenueArtShade: {
    ...StyleSheet.absoluteFillObject,
  },
  homeHeroVisibleInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  homeHeroVisibleInfoCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homeHeroPresenceEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 0,
  },
  homeHeroPresenceEyebrowDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.visibilityOn,
  },
  homeHeroPresenceEyebrowDotHidden: {
    backgroundColor: T.visibilityOff,
  },
  homeHeroPresenceEyebrowDotError: {
    backgroundColor: T.danger,
  },
  homeHeroPresenceEyebrow: {
    color: T.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
    letterSpacing: 0.9,
  },
  homeHeroPresenceEyebrowHidden: {
    color: T.textPrimary,
  },
  homeHeroPresenceEyebrowError: {
    color: T.dangerText,
  },
  homeHeroVenueNameVisible: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 21,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.25,
    maxWidth: "100%",
  },
  homeHeroCardCopyVisible: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
    maxWidth: "100%",
  },
  homeVisibleHeroButtonInline: {
    width: 150,
    minHeight: 70,
    borderRadius: 16,
    backgroundColor: T.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 0,
  },
  homeVisibleHeroButtonInlineHidden: {
    backgroundColor: T.primary,
  },
  homeVisibleHeroButtonInlineError: {
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.dangerBorder,
  },
  homeVisibleHeroButtonMark: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: T.surfaceGlassLilac,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  homeVisibleHeroButtonTextInline: {
    color: T.white,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyBold,
    textAlign: "left",
    maxWidth: 82,
  },
  homeVisibleHeroButtonTextInlineHidden: {
    color: T.white,
  },
  homeHeroVisibleDivider: {
    height: 1,
    backgroundColor: T.border,
  },
  homeHeroPrivacyRowVisible: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  homeHeroPrivacyIconWrapVisible: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: T.surfaceMid,
    alignItems: "center",
    justifyContent: "center",
  },
  homeHeroPrivacyCopyVisible: {
    flex: 1,
    minWidth: 0,
  },
  homeHeroPrivacyTextVisible: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeHeroPrivacySeparator: {
    color: T.textMuted,
  },
  homeHeroPrivacyHighlightVisible: {
    color: T.textPrimary,
    fontFamily: T.fontBodyBold,
  },
  homeExploreHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 8,
  },
  homeExploreHeaderCopy: {
    gap: 4,
  },
  homeExploreTitle: {
    color: T.textPrimary,
    fontSize: 21,
    lineHeight: 25,
    fontFamily: T.fontBodyMedium,
  },
  homeExploreMeta: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  homeExploreSideNote: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeVenueGrid: {
    flexDirection: "column",
    gap: 8,
    marginBottom: 0,
  },
  homeVenueGridSingle: {
    flexDirection: "column",
  },
  homeVenueCard: {
    flex: 1,
    minHeight: 112,
    borderRadius: 22,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 13,
    shadowColor: T.primary,
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  homeVenueCardSingle: {
    flex: 1,
    minHeight: 114,
  },
  homeVenueCardRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  homeVenueThumb: {
    width: 96,
    height: 96,
    borderRadius: 18,
    overflow: "hidden",
    position: "relative",
    flexShrink: 0,
  },
  homeVenueThumbFeatured: {
    borderWidth: 1,
    borderColor: T.borderBlack,
  },
  homeVenueCardBody: {
    flex: 1,
    justifyContent: "space-between",
    gap: 6,
  },
  homeVenueCardTopGroup: {
    gap: 4,
  },
  homeVenueCardName: {
    color: T.textPrimary,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
    marginBottom: 0,
    flex: 1,
  },
  homeVenueCardNameFeatured: {
    fontSize: 15,
    lineHeight: 18,
  },
  homeVenueStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingTop: 0,
  },
  homeVenueStatusText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  homeVenuePeopleRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  homeVenueSignalIconWrap: {
    minHeight: 20,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  homeVenueSignalBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    marginLeft: 2,
  },
  homeVenueSignalBar: {
    width: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  homeVenueSignalBarActive: {
    backgroundColor: T.primary,
    borderColor: T.primary,
  },
  homeVenueSignalBarInactive: {
    backgroundColor: T.surfaceGlassUltra,
  },
  homeVenueDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  homeVenueDistanceText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeVenueChevronBubble: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceGlassUltra,
    borderWidth: 1,
    borderColor: T.border,
    alignSelf: "center",
  },
  homeSafetyCard: {
    minHeight: 70,
    borderRadius: 22,
    backgroundColor: T.surfaceGlass,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: T.primary,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  homeSafetyCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  homeSafetyCardIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceMid,
  },
  homeSafetyCardCopy: {
    flex: 1,
    gap: 1,
  },
  homeSafetyCardTitle: {
    color: T.primary,
    fontSize: 14,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  homeSafetyCardSubtitle: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 14,
    fontFamily: T.fontBodyMedium,
  },
  homePrivateMapTexture: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: T.surfaceDim,
  },
} as const;
