import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const onboardingStyles = {
  onboardingPage: {
    position: "relative",
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  onboardingHeader: {
    gap: 16,
    marginBottom: 26,
    zIndex: 1,
  },
  onboardingHeaderRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  onboardingBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceDim,
  },
  onboardingStepBadge: {
    minHeight: 34,
    paddingHorizontal: 15,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: T.surfaceDim,
  },
  onboardingStepBadgeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.onboardingAccent,
  },
  onboardingStepBadgeText: {
    color: T.onboardingInk,
    fontSize: 11,
    letterSpacing: 0.8,
    fontFamily: T.fontBodyBold,
  },
  onboardingHeaderMark: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingProgress: {
    position: "relative",
    height: 18,
    justifyContent: "center",
  },
  onboardingProgressRail: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 5,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: T.onboardingBorder,
  },
  onboardingProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: T.onboardingAccent,
  },
  onboardingProgressNodes: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  onboardingProgressNode: {
    position: "absolute",
    top: 4,
    width: 10,
    height: 10,
    marginLeft: -5,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: T.onboardingBorderStrong,
    backgroundColor: T.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingProgressNodeComplete: {
    borderColor: T.onboardingAccent,
    backgroundColor: T.onboardingAccent,
  },
  onboardingProgressNodeCurrent: {
    borderWidth: 3,
    borderColor: T.onboardingAccent,
    backgroundColor: T.onboardingAccentSoft,
    transform: [{ scale: 1.35 }],
  },
  onboardingContent: {
    gap: 28,
    zIndex: 1,
  },
  onboardingFooter: {
    marginTop: "auto",
    paddingTop: 28,
    zIndex: 1,
  },
  onboardingIntroBlock: {
    gap: 12,
  },
  onboardingTitle: {
    maxWidth: 370,
    color: T.onboardingInk,
    fontSize: 38,
    lineHeight: 42,
    letterSpacing: -1.5,
    fontFamily: T.fontDisplayBold,
  },
  onboardingBody: {
    maxWidth: 355,
    color: T.onboardingInkSoft,
    fontSize: 15,
    lineHeight: 23,
    fontFamily: T.fontBody,
  },
  onboardingTitleCentered: {
    alignSelf: "center",
    textAlign: "center",
  },
  onboardingPermissionHeroIcon: {
    width: 104,
    height: 104,
    marginBottom: 12,
    alignSelf: "center",
    borderRadius: 52,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingPermissionHeroBadge: {
    position: "absolute",
    right: 4,
    bottom: 4,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccent,
    borderWidth: 3,
    borderColor: T.surface,
  },
  onboardingNameBlock: {
    marginTop: 36,
    gap: 28,
  },
  onboardingEyebrowBadge: {
    minHeight: 28,
    alignSelf: "flex-start",
    paddingHorizontal: 11,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingEyebrowBadgeText: {
    color: T.onboardingInk,
    fontSize: 10,
    letterSpacing: 1.1,
    fontFamily: T.fontBodyBold,
  },
  onboardingProfileHero: {
    alignItems: "center",
    gap: 7,
    paddingVertical: 4,
  },
  onboardingProfileEditBadge: {
    position: "absolute",
    top: 78,
    marginLeft: 88,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccent,
    borderWidth: 3,
    borderColor: T.surface,
  },
  onboardingProfileHeroTitle: {
    marginTop: 3,
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingProfileHeroBody: {
    color: T.onboardingInkSoft,
    fontSize: 11,
    fontFamily: T.fontBodyMedium,
  },
  onboardingProfileForm: {
    gap: 8,
  },
  onboardingFieldLabel: {
    color: T.onboardingInk,
    fontSize: 12,
    fontFamily: T.fontBodyBold,
  },
  onboardingNameInput: {
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceDim,
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 22,
    fontFamily: T.fontBodyMedium,
  },
  onboardingShapeSection: {
    gap: 12,
  },
  onboardingShapeSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  onboardingShapeSelection: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    fontFamily: T.fontBodyMedium,
  },
  onboardingShapeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  onboardingShapeOption: {
    flex: 1,
    minHeight: 68,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceDim,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingShapeOptionActive: {
    borderWidth: 2,
    borderColor: T.onboardingAccent,
    backgroundColor: T.onboardingAccentFaint,
  },
  onboardingShapeCheck: {
    position: "absolute",
    right: 5,
    top: 5,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccent,
  },
  onboardingProfileTrustCard: {
    padding: 14,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingProfileTrustIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingGreeting: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  onboardingGreetingIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingGreetingText: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingAvatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  onboardingAvatarTile: {
    width: "48%",
    minHeight: 145,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.glassLight,
    alignItems: "center",
    justifyContent: "center",
    gap: 13,
    padding: 14,
  },
  onboardingAvatarTileActive: {
    borderWidth: 2,
    borderColor: T.onboardingInk,
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingAvatarCheck: {
    position: "absolute",
    right: 10,
    top: 10,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: T.onboardingInk,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  onboardingAvatarHalo: {
    borderRadius: 999,
    shadowColor: T.onboardingAccent,
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  onboardingAvatarShape: {
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingAvatarGeometric: {
    borderRadius: 21,
  },
  onboardingAvatarAbstract: {
    borderTopLeftRadius: 36,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 38,
  },
  onboardingAvatarMinimal: {
    borderRadius: 999,
  },
  onboardingAvatarSoft: {
    borderTopLeftRadius: 42,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 46,
    transform: [{ rotate: "-6deg" }],
  },
  onboardingAvatarEchoOne: {
    position: "absolute",
    width: "60%",
    height: "60%",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(198,227,133,0.55)",
  },
  onboardingAvatarEchoTwo: {
    position: "absolute",
    width: "34%",
    height: "34%",
    borderRadius: 999,
    backgroundColor: "rgba(198,227,133,0.42)",
  },
  onboardingAvatarOrbitCore: {
    width: "48%",
    height: "48%",
    borderRadius: 999,
    backgroundColor: T.onboardingInk,
    borderWidth: 5,
    borderColor: "rgba(255,255,255,0.48)",
  },
  onboardingAvatarPebbleGlow: {
    width: "58%",
    height: "58%",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  onboardingAvatarLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.985 }],
  },
  onboardingSurpriseButton: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.glassLight,
  },
  onboardingSurpriseLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewBlock: {
    gap: 12,
    marginTop: 6,
  },
  onboardingSectionTitle: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewCard: {
    minHeight: 100,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceGlassSoft,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...leftShadows.small,
  },
  onboardingPreviewCopy: {
    flex: 1,
    gap: 7,
  },
  onboardingPreviewName: {
    color: T.onboardingInk,
    fontSize: 18,
    fontFamily: T.fontDisplayBold,
  },
  onboardingPreviewStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  onboardingPreviewStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.onboardingAccent,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
  },
  onboardingPreviewStatus: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionFlow: {
    alignItems: "stretch",
    gap: 8,
  },
  onboardingDetectionStep: {
    width: "100%",
    minHeight: 64,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  onboardingDetectionNumber: {
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionNumberText: {
    color: T.onboardingInk,
    fontSize: 12,
    fontFamily: T.fontBodyBold,
  },
  onboardingDetectionIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: T.onboardingAccentMedium,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionLabel: {
    flex: 1,
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionConnector: {
    height: 10,
    marginLeft: 26,
    alignSelf: "flex-start",
    borderLeftWidth: 1,
    borderStyle: "dashed",
    borderColor: T.onboardingBorderStrong,
  },
  onboardingPrivacyCard: {
    padding: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  onboardingPermissionList: {
    gap: 12,
  },
  onboardingSafetyFeatureList: {
    gap: 12,
  },
  onboardingSafetyFeatureCard: {
    minHeight: 96,
    padding: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingSafetyFeatureIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceCard,
  },
  onboardingSafetyFeatureTitle: {
    color: T.onboardingInk,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: T.fontBodyBold,
  },
  onboardingSafetyFeatureBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingPrivacyQuote: {
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: T.onboardingAccentFaint,
  },
  onboardingPrivacyQuoteRule: {
    width: 5,
    height: 48,
    borderRadius: 3,
    backgroundColor: T.onboardingAccent,
  },
  onboardingPrivacyQuoteText: {
    flex: 1,
    color: T.onboardingInkSoft,
    fontSize: 14,
    lineHeight: 21,
    fontStyle: "italic",
    fontFamily: T.fontBody,
  },
  onboardingPermissionLink: {
    minHeight: 44,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  onboardingPermissionLinkText: {
    color: T.onboardingAccent,
    fontSize: 13,
    textDecorationLine: "underline",
    fontFamily: T.fontBodyBold,
  },
  onboardingPrivacyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingPrivacyCopy: {
    flex: 1,
    gap: 6,
  },
  onboardingPrivacyTitle: {
    color: T.onboardingInk,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  onboardingPrivacyBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingError: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  onboardingRecoveryCard: {
    padding: 14,
    borderRadius: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    backgroundColor: T.dangerDim,
  },
  onboardingSettingsButton: {
    minHeight: 44,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
  },
  onboardingSettingsLabel: {
    color: T.onboardingInk,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  onboardingPermissionFooter: {
    gap: 8,
  },
  onboardingNotNowButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingNotNowLabel: {
    color: T.onboardingInkSoft,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingMomentList: {
    gap: 12,
  },
  onboardingMomentRow: {
    minHeight: 78,
    padding: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  onboardingMomentIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentMedium,
  },
  onboardingMomentCopy: {
    flex: 1,
    gap: 4,
  },
  onboardingMomentTitle: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingMomentBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingPermissionNote: {
    color: T.onboardingInkMuted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    fontFamily: T.fontBodyMedium,
  },
  onboardingRuleList: {
    paddingHorizontal: 12,
  },
  onboardingRuleCard: {
    overflow: "hidden",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
    ...leftShadows.small,
  },
  onboardingRuleHeader: {
    minHeight: 68,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: T.onboardingAccentFaint,
    borderBottomWidth: 1,
    borderBottomColor: T.onboardingBorder,
  },
  onboardingRuleHeaderIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentMedium,
  },
  onboardingRuleHeaderCopy: {
    flex: 1,
    gap: 3,
  },
  onboardingRuleHeaderTitle: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingRuleHeaderBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    fontFamily: T.fontBody,
  },
  onboardingRuleRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  onboardingRuleRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  onboardingRuleNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingRuleNumberText: {
    color: T.onboardingInk,
    fontSize: 11,
    fontFamily: T.fontBodyBold,
  },
  onboardingRuleText: {
    flex: 1,
    color: T.onboardingInk,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  onboardingPrincipleList: {
    gap: 12,
  },
  onboardingPrincipleCard: {
    minHeight: 104,
    padding: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingPrincipleIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingPrincipleCopy: {
    flex: 1,
    gap: 5,
  },
  onboardingPrincipleTitle: {
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  onboardingPrincipleBody: {
    color: T.onboardingInkSoft,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBody,
  },
  onboardingPledgeCard: {
    padding: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingPledgeCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingPledgeCopy: {
    flex: 1,
    gap: 5,
  },
  onboardingPledgeTitle: {
    color: T.onboardingInk,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: T.fontBodyBold,
  },
  onboardingPledgeBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingPledgeLink: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  onboardingPledgeLinkText: {
    color: T.onboardingAccent,
    fontSize: 12,
    textDecorationLine: "underline",
    fontFamily: T.fontBodyBold,
  },
  onboardingSafetyStatement: {
    color: T.onboardingInkSoft,
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
    fontFamily: T.fontBodyBold,
  },
  onboardingLegalPending: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderWidth: 1,
    borderColor: T.warningBorder,
    backgroundColor: T.visibilityOffSoft,
  },
  onboardingLegalPendingText: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  onboardingLegalSection: {
    gap: 10,
  },
  onboardingFinalPolicyList: {
    gap: 12,
  },
  onboardingFinalPolicyRow: {
    minHeight: 80,
    paddingHorizontal: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    backgroundColor: T.surfaceDim,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingFinalPolicyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceCard,
    ...leftShadows.small,
  },
  onboardingFinalPolicyTitle: {
    color: T.onboardingInk,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  onboardingFinalPolicySummary: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBody,
  },
  onboardingFinalConsent: {
    marginTop: 8,
    padding: 16,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: T.onboardingAccentFaint,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  onboardingLegalSectionHeader: {
    paddingHorizontal: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  onboardingLegalSectionHint: {
    marginTop: 3,
    color: T.onboardingInkMuted,
    fontSize: 11,
    fontFamily: T.fontBodyMedium,
  },
  onboardingLegalList: {
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
  },
  onboardingLegalRow: {
    minHeight: 62,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  onboardingLegalRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  onboardingLegalCheck: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingLegalCheckActive: {
    backgroundColor: T.onboardingInk,
    borderColor: T.onboardingInk,
  },
  onboardingLegalPendingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: T.visibilityOff,
  },
  onboardingLegalDocumentIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingLegalLinkButton: {
    flex: 1,
    gap: 4,
  },
  onboardingLegalLink: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  onboardingLegalStatus: {
    color: T.textMuted,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  onboardingLegalSummary: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBody,
  },
  onboardingCompleteHero: {
    minHeight: 330,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  onboardingOrbitOuter: {
    width: 210,
    height: 210,
    borderRadius: 105,
    borderWidth: 1,
    borderColor: T.onboardingDecorativeBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingOrbitInner: {
    width: 178,
    height: 178,
    borderRadius: 89,
    borderWidth: 1,
    borderColor: "rgba(198,227,133,0.48)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentFaint,
  },
  onboardingSparkle: {
    position: "absolute",
    color: T.onboardingAccent,
    fontSize: 28,
    textShadowColor: "rgba(31,14,6,0.25)",
    textShadowRadius: 1,
    zIndex: 2,
  },
  onboardingSparkleOne: {
    left: 36,
    top: 76,
  },
  onboardingSparkleTwo: {
    right: 44,
    top: 44,
  },
  onboardingSparkleThree: {
    right: 28,
    top: 188,
  },
  onboardingCompleteName: {
    color: T.onboardingInk,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1,
  },
  onboardingCompleteSignal: {
    color: T.onboardingInkSoft,
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingReadyCard: {
    minHeight: 124,
    justifyContent: "center",
    padding: 26,
  },
  onboardingReadyBadge: {
    position: "absolute",
    top: -20,
    alignSelf: "center",
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.onboardingAccent,
    borderWidth: 4,
    borderColor: T.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingReadyText: {
    maxWidth: 290,
    color: T.onboardingInk,
    fontSize: 24,
    lineHeight: 31,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
} as const;
