import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const onboardingStyles = {
  onboardingPage: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  onboardingHeader: {
    gap: 24,
    marginBottom: 40,
  },
  onboardingProgress: {
    flexDirection: "row",
    gap: 8,
  },
  onboardingProgressTrack: {
    width: 28,
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(31,14,6,0.16)",
  },
  onboardingProgressTrackActive: {
    backgroundColor: T.onboardingAccent,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.28)",
  },
  onboardingContent: {
    gap: 28,
  },
  onboardingFooter: {
    marginTop: "auto",
    paddingTop: 40,
  },
  onboardingIntroBlock: {
    gap: 12,
  },
  onboardingTitle: {
    maxWidth: 330,
    color: T.onboardingInk,
    fontSize: 38,
    lineHeight: 42,
    letterSpacing: -1.5,
    fontFamily: T.fontDisplayBold,
  },
  onboardingBody: {
    maxWidth: 355,
    color: "rgba(31,14,6,0.68)",
    fontSize: 15,
    lineHeight: 23,
    fontFamily: T.fontBody,
  },
  onboardingNameBlock: {
    marginTop: 64,
    gap: 28,
  },
  onboardingNameInput: {
    minHeight: 64,
    paddingHorizontal: 4,
    paddingVertical: 10,
    borderBottomWidth: 1.5,
    borderBottomColor: T.onboardingInk,
    color: T.onboardingInk,
    fontSize: 29,
    lineHeight: 36,
    fontFamily: T.fontDisplay,
  },
  onboardingGreeting: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  onboardingGreetingIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingGreetingText: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingAvatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  onboardingAvatarTile: {
    width: "48%",
    minHeight: 145,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.14)",
    backgroundColor: "rgba(255,255,255,0.58)",
    alignItems: "center",
    justifyContent: "center",
    gap: 13,
    padding: 14,
  },
  onboardingAvatarTileActive: {
    borderWidth: 2,
    borderColor: T.onboardingInk,
    backgroundColor: "rgba(198,227,133,0.18)",
  },
  onboardingAvatarCheck: {
    position: "absolute",
    right: 10,
    top: 10,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: T.onboardingInk,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  onboardingAvatarHalo: {
    borderRadius: 999,
    shadowColor: T.onboardingAccent,
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  onboardingAvatarShape: {
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingAvatarGeometric: {
    borderRadius: 21,
  },
  onboardingAvatarAbstract: {
    borderTopLeftRadius: 36,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 38,
  },
  onboardingAvatarMinimal: {
    borderRadius: 999,
  },
  onboardingAvatarSoft: {
    borderTopLeftRadius: 42,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 46,
    transform: [{ rotate: "-6deg" }],
  },
  onboardingAvatarEchoOne: {
    position: "absolute",
    width: "60%",
    height: "60%",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(198,227,133,0.55)",
  },
  onboardingAvatarEchoTwo: {
    position: "absolute",
    width: "34%",
    height: "34%",
    borderRadius: 999,
    backgroundColor: "rgba(198,227,133,0.42)",
  },
  onboardingAvatarOrbitCore: {
    width: "48%",
    height: "48%",
    borderRadius: 999,
    backgroundColor: T.onboardingInk,
    borderWidth: 5,
    borderColor: "rgba(255,255,255,0.48)",
  },
  onboardingAvatarPebbleGlow: {
    width: "58%",
    height: "58%",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  onboardingAvatarLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.985 }],
  },
  onboardingSurpriseButton: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.16)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.46)",
  },
  onboardingSurpriseLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewBlock: {
    gap: 12,
    marginTop: 6,
  },
  onboardingSectionTitle: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewCard: {
    minHeight: 100,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.14)",
    backgroundColor: "rgba(255,255,255,0.64)",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...leftShadows.small,
  },
  onboardingPreviewCopy: {
    flex: 1,
    gap: 7,
  },
  onboardingPreviewName: {
    color: T.onboardingInk,
    fontSize: 18,
    fontFamily: T.fontDisplayBold,
  },
  onboardingPreviewStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  onboardingPreviewStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.onboardingAccent,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.35)",
  },
  onboardingPreviewStatus: {
    color: "rgba(31,14,6,0.64)",
    fontSize: 12,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionFlow: {
    alignItems: "center",
    paddingVertical: 4,
  },
  onboardingDetectionStep: {
    width: "100%",
    alignItems: "center",
    gap: 9,
  },
  onboardingDetectionNumber: {
    position: "absolute",
    left: 34,
    top: 24,
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.16)",
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionNumberText: {
    color: T.onboardingInk,
    fontSize: 12,
    fontFamily: T.fontBodyBold,
  },
  onboardingDetectionIcon: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "rgba(198,227,133,0.22)",
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionConnector: {
    width: 1,
    height: 28,
    marginVertical: 6,
    borderLeftWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(31,14,6,0.35)",
  },
  onboardingPrivacyCard: {
    padding: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  onboardingPrivacyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingPrivacyCopy: {
    flex: 1,
    gap: 6,
  },
  onboardingPrivacyTitle: {
    color: T.onboardingInk,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  onboardingPrivacyBody: {
    color: "rgba(31,14,6,0.58)",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingError: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  onboardingCompleteHero: {
    minHeight: 330,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  onboardingOrbitOuter: {
    width: 210,
    height: 210,
    borderRadius: 105,
    borderWidth: 1,
    borderColor: "rgba(31,14,6,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingOrbitInner: {
    width: 178,
    height: 178,
    borderRadius: 89,
    borderWidth: 1,
    borderColor: "rgba(198,227,133,0.48)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(198,227,133,0.08)",
  },
  onboardingSparkle: {
    position: "absolute",
    color: T.onboardingAccent,
    fontSize: 28,
    textShadowColor: "rgba(31,14,6,0.25)",
    textShadowRadius: 1,
    zIndex: 2,
  },
  onboardingSparkleOne: {
    left: 36,
    top: 76,
  },
  onboardingSparkleTwo: {
    right: 44,
    top: 44,
  },
  onboardingSparkleThree: {
    right: 28,
    top: 188,
  },
  onboardingCompleteName: {
    color: T.onboardingInk,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1,
  },
  onboardingCompleteSignal: {
    color: "rgba(31,14,6,0.62)",
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingReadyCard: {
    minHeight: 124,
    justifyContent: "center",
    padding: 26,
  },
  onboardingReadyBadge: {
    position: "absolute",
    top: -20,
    alignSelf: "center",
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.onboardingAccent,
    borderWidth: 4,
    borderColor: T.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingReadyText: {
    maxWidth: 290,
    color: T.onboardingInk,
    fontSize: 24,
    lineHeight: 31,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
} as const;
