import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const onboardingStyles = {
  onboardingPage: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  onboardingHeader: {
    gap: 18,
    marginBottom: 30,
  },
  onboardingHeaderRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  onboardingBackButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingProgress: {
    flexDirection: "row",
    gap: 8,
  },
  onboardingProgressTrack: {
    flex: 1,
    height: 7,
    borderRadius: 999,
    backgroundColor: T.onboardingBorder,
  },
  onboardingProgressTrackActive: {
    backgroundColor: T.onboardingAccent,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
  },
  onboardingContent: {
    gap: 28,
  },
  onboardingFooter: {
    marginTop: "auto",
    paddingTop: 28,
  },
  onboardingIntroBlock: {
    gap: 12,
  },
  onboardingTitle: {
    maxWidth: 330,
    color: T.onboardingInk,
    fontSize: 38,
    lineHeight: 42,
    letterSpacing: -1.5,
    fontFamily: T.fontDisplayBold,
  },
  onboardingBody: {
    maxWidth: 355,
    color: T.onboardingInkSoft,
    fontSize: 15,
    lineHeight: 23,
    fontFamily: T.fontBody,
  },
  onboardingNameBlock: {
    marginTop: 36,
    gap: 28,
  },
  onboardingNameInput: {
    minHeight: 64,
    paddingHorizontal: 4,
    paddingVertical: 10,
    borderBottomWidth: 1.5,
    borderBottomColor: T.onboardingInk,
    color: T.onboardingInk,
    fontSize: 29,
    lineHeight: 36,
    fontFamily: T.fontDisplay,
  },
  onboardingGreeting: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  onboardingGreetingIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingGreetingText: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingAvatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  onboardingAvatarTile: {
    width: "48%",
    minHeight: 145,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.glassLight,
    alignItems: "center",
    justifyContent: "center",
    gap: 13,
    padding: 14,
  },
  onboardingAvatarTileActive: {
    borderWidth: 2,
    borderColor: T.onboardingInk,
    backgroundColor: T.onboardingAccentSoft,
  },
  onboardingAvatarCheck: {
    position: "absolute",
    right: 10,
    top: 10,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: T.onboardingInk,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  onboardingAvatarHalo: {
    borderRadius: 999,
    shadowColor: T.onboardingAccent,
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  onboardingAvatarShape: {
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingAvatarGeometric: {
    borderRadius: 21,
  },
  onboardingAvatarAbstract: {
    borderTopLeftRadius: 36,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 38,
  },
  onboardingAvatarMinimal: {
    borderRadius: 999,
  },
  onboardingAvatarSoft: {
    borderTopLeftRadius: 42,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 46,
    transform: [{ rotate: "-6deg" }],
  },
  onboardingAvatarEchoOne: {
    position: "absolute",
    width: "60%",
    height: "60%",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(95,115,63,0.55)",
  },
  onboardingAvatarEchoTwo: {
    position: "absolute",
    width: "34%",
    height: "34%",
    borderRadius: 999,
    backgroundColor: "rgba(95,115,63,0.42)",
  },
  onboardingAvatarOrbitCore: {
    width: "48%",
    height: "48%",
    borderRadius: 999,
    backgroundColor: T.onboardingInk,
    borderWidth: 5,
    borderColor: "rgba(255,255,255,0.48)",
  },
  onboardingAvatarPebbleGlow: {
    width: "58%",
    height: "58%",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  onboardingAvatarLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.985 }],
  },
  onboardingSurpriseButton: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.glassLight,
  },
  onboardingSurpriseLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewBlock: {
    gap: 12,
    marginTop: 6,
  },
  onboardingSectionTitle: {
    color: T.onboardingInk,
    fontSize: 15,
    fontFamily: T.fontBodyBold,
  },
  onboardingPreviewCard: {
    minHeight: 100,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceGlassSoft,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...leftShadows.small,
  },
  onboardingPreviewCopy: {
    flex: 1,
    gap: 7,
  },
  onboardingPreviewName: {
    color: T.onboardingInk,
    fontSize: 18,
    fontFamily: T.fontDisplayBold,
  },
  onboardingPreviewStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  onboardingPreviewStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.onboardingAccent,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
  },
  onboardingPreviewStatus: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionFlow: {
    alignItems: "center",
    paddingVertical: 4,
  },
  onboardingDetectionStep: {
    width: "100%",
    alignItems: "center",
    gap: 9,
  },
  onboardingDetectionNumber: {
    position: "absolute",
    left: 34,
    top: 24,
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionNumberText: {
    color: T.onboardingInk,
    fontSize: 12,
    fontFamily: T.fontBodyBold,
  },
  onboardingDetectionIcon: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: T.onboardingAccentMedium,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingDetectionLabel: {
    color: T.onboardingInk,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  onboardingDetectionConnector: {
    width: 1,
    height: 28,
    marginVertical: 6,
    borderLeftWidth: 1,
    borderStyle: "dashed",
    borderColor: T.onboardingBorderStrong,
  },
  onboardingPrivacyCard: {
    padding: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  onboardingPermissionList: {
    gap: 12,
  },
  onboardingPrivacyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingPrivacyCopy: {
    flex: 1,
    gap: 6,
  },
  onboardingPrivacyTitle: {
    color: T.onboardingInk,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  onboardingPrivacyBody: {
    color: T.onboardingInkSoft,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  onboardingError: {
    color: T.dangerText,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  onboardingRecoveryCard: {
    padding: 14,
    borderRadius: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    backgroundColor: T.dangerDim,
  },
  onboardingSettingsButton: {
    minHeight: 44,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
  },
  onboardingSettingsLabel: {
    color: T.onboardingInk,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  onboardingLegalPending: {
    padding: 14,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderWidth: 1,
    borderColor: T.warningBorder,
    backgroundColor: T.visibilityOffSoft,
  },
  onboardingLegalPendingText: {
    flex: 1,
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBodyMedium,
  },
  onboardingLegalList: {
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.surfaceCard,
  },
  onboardingLegalRow: {
    minHeight: 74,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  onboardingLegalCheck: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingLegalCheckActive: {
    backgroundColor: T.onboardingInk,
    borderColor: T.onboardingInk,
  },
  onboardingLegalPendingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: T.visibilityOff,
  },
  onboardingLegalLinkButton: {
    flex: 1,
    gap: 4,
  },
  onboardingLegalLink: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    textDecorationLine: "underline",
    fontFamily: T.fontBodyBold,
  },
  onboardingLegalStatus: {
    color: T.textMuted,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  onboardingLegalSummary: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBody,
  },
  onboardingCompleteHero: {
    minHeight: 330,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  onboardingOrbitOuter: {
    width: 210,
    height: 210,
    borderRadius: 105,
    borderWidth: 1,
    borderColor: T.onboardingDecorativeBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingOrbitInner: {
    width: 178,
    height: 178,
    borderRadius: 89,
    borderWidth: 1,
    borderColor: "rgba(95,115,63,0.48)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.onboardingAccentFaint,
  },
  onboardingSparkle: {
    position: "absolute",
    color: T.onboardingAccent,
    fontSize: 28,
    textShadowColor: "rgba(26,24,21,0.25)",
    textShadowRadius: 1,
    zIndex: 2,
  },
  onboardingSparkleOne: {
    left: 36,
    top: 76,
  },
  onboardingSparkleTwo: {
    right: 44,
    top: 44,
  },
  onboardingSparkleThree: {
    right: 28,
    top: 188,
  },
  onboardingCompleteName: {
    color: T.onboardingInk,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -1,
  },
  onboardingCompleteSignal: {
    color: T.onboardingInkSoft,
    fontSize: 15,
    fontFamily: T.fontBodyMedium,
  },
  onboardingReadyCard: {
    minHeight: 124,
    justifyContent: "center",
    padding: 26,
  },
  onboardingReadyBadge: {
    position: "absolute",
    top: -20,
    alignSelf: "center",
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.onboardingAccent,
    borderWidth: 4,
    borderColor: T.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingReadyText: {
    maxWidth: 290,
    color: T.onboardingInk,
    fontSize: 24,
    lineHeight: 31,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.6,
  },
} as const;
