import { T } from "../../theme";
import { leftShadows } from "../../shadow";

export const preAuthStyles = {
  preAuthWrap: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 20,
    backgroundColor: T.surface,
    justifyContent: "space-between",
  },
  preAuthGlow: {
    position: "absolute",
    top: -180,
    left: -120,
    right: -120,
    height: 520,
    borderRadius: 260,
  },
  preAuthAmbientLayer: {
    ...({ position: "absolute", top: 0, right: 0, bottom: 0, left: 0 } as const),
    opacity: 0.82,
  },
  preAuthAmbientOrb: {
    position: "absolute",
    borderRadius: 999,
    borderWidth: 1,
  },
  preAuthAmbientOrbOne: {
    width: 290,
    height: 290,
    top: 72,
    left: -188,
    backgroundColor: "rgba(198,227,133,0.12)",
    borderColor: "rgba(198,227,133,0.14)",
  },
  preAuthAmbientOrbTwo: {
    width: 255,
    height: 255,
    right: -164,
    bottom: 76,
    backgroundColor: "rgba(228,200,155,0.10)",
    borderColor: "rgba(228,200,155,0.13)",
  },
  preAuthAmbientOrbThree: {
    width: 145,
    height: 145,
    left: -74,
    bottom: -52,
    backgroundColor: "rgba(199,220,215,0.11)",
    borderColor: "rgba(199,220,215,0.14)",
  },
  preAuthAmbientArc: {
    position: "absolute",
    width: 430,
    height: 430,
    top: 188,
    right: -286,
    borderRadius: 215,
    borderWidth: 1,
    borderColor: "rgba(22,22,22,0.045)",
    transform: [{ rotate: "-18deg" }],
  },
  preAuthHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 2,
  },
  preAuthBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  preAuthLogoRing: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
    backgroundColor: T.onboardingAccent,
    alignItems: "center",
    justifyContent: "center",
    ...leftShadows.small,
  },
  preAuthWordmark: {
    color: T.onboardingInk,
    fontSize: 12,
    letterSpacing: 3.2,
    fontFamily: T.fontBodyBold,
  },
  preAuthSkip: {
    minHeight: 38,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  preAuthSkipLabel: {
    color: T.onboardingInkSoft,
    fontSize: 14,
    fontFamily: T.fontBodyMedium,
  },
  preAuthMain: {
    flex: 1,
    justifyContent: "center",
    gap: 20,
    paddingVertical: 12,
  },
  preAuthVisual: {
    height: 190,
    alignItems: "center",
    justifyContent: "center",
  },
  preAuthVisualHalo: {
    position: "absolute",
    width: 178,
    height: 178,
    borderRadius: 89,
  },
  preAuthVisualRing: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  preAuthVisualCore: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 8,
    borderColor: T.glassBorder,
    ...leftShadows.small,
  },
  preAuthSignalDot: {
    position: "absolute",
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: T.surface,
  },
  preAuthSignalDotOne: {
    top: 16,
    left: 104,
  },
  preAuthSignalDotTwo: {
    right: 84,
    top: 52,
  },
  preAuthSignalDotThree: {
    bottom: 14,
    left: 118,
  },
  preAuthVisualOrbit: {
    position: "absolute",
    width: 190,
    height: 108,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.onboardingBorderStrong,
    transform: [{ rotate: "-18deg" }],
  },
  preAuthOrbitDot: {
    position: "absolute",
    top: -8,
    right: 30,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: T.surface,
  },
  preAuthPrivacyPill: {
    position: "absolute",
    bottom: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: T.glassLightMedium,
    borderWidth: 1,
    borderColor: T.onboardingBorder,
  },
  preAuthPrivacyPillText: {
    color: T.onboardingInk,
    fontSize: 10,
    letterSpacing: 1.3,
    fontFamily: T.fontBodyBold,
  },
  preAuthCopy: {
    gap: 12,
  },
  preAuthEyebrow: {
    color: T.onboardingInkMuted,
    fontSize: 11,
    letterSpacing: 2.4,
    fontFamily: T.fontBodyBold,
  },
  preAuthTitle: {
    maxWidth: 380,
    color: T.onboardingInk,
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1.5,
    fontFamily: T.fontDisplayBold,
  },
  preAuthBody: {
    maxWidth: 370,
    color: T.onboardingInkSoft,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  preAuthDetailCard: {
    minHeight: 64,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  preAuthDetailIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  preAuthDetailText: {
    flex: 1,
    color: T.onboardingInk,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  preAuthDetailCount: {
    color: T.onboardingInkMuted,
    fontSize: 11,
    letterSpacing: 1,
    fontFamily: T.fontBodyBold,
  },
  preAuthFooter: {
    gap: 14,
  },
  preAuthProgress: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 2,
  },
  preAuthProgressDot: {
    width: 24,
    height: 5,
    borderRadius: 999,
    backgroundColor: T.onboardingBorder,
  },
  preAuthProgressDotActive: {
    width: 48,
    backgroundColor: T.onboardingInk,
  },
  preAuthFootnote: {
    color: T.onboardingInkMuted,
    fontSize: 12,
    textAlign: "center",
    fontFamily: T.fontBodyMedium,
  },
  preAuthPressed: {
    opacity: 0.72,
  },
} as const;