import { T } from "../../theme";

export const profileStyles = {
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  profileHeroBlock: {
    alignItems: "center",
    gap: 10,
    marginBottom: 28,
  },
  profileName: {
    color: T.textPrimary,
    fontSize: 28,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.6,
    textAlign: "center",
  },
  profileIntent: {
    color: T.textSecondary,
    fontSize: 14,
    textTransform: "capitalize",
  },
  chipWrapCenter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  profileSections: {
    gap: 4,
    marginBottom: 28,
  },
  profileActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  profileDestructive: {
    gap: 10,
    marginBottom: 20,
  },
  profileActionHint: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  reportPanel: {
    gap: 14,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    borderRadius: T.radiusLg,
    backgroundColor: T.dangerDim,
    padding: 16,
  },
  reportPanelTitle: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  reportPanelHint: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: -8,
  },
  reportChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mePage: {
    gap: 20,
  },
  meTopRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  profilePage: {
    gap: 18,
    paddingTop: 6,
  },
  profileTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileHeaderButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  profileEditHeaderButton: {
    minWidth: 58,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  profileEditHeaderText: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHeaderTitle: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHeroCard: {
    alignItems: "center",
    gap: 10,
    paddingTop: 4,
    paddingBottom: 2,
  },
  profileBrandHalo: {
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: "rgba(255,250,242,0.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#E7C890",
    shadowOpacity: 0.2,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
    position: "relative",
  },
  profileBrandCore: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(233,236,206,0.86)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileBrandSparkOne: {
    position: "absolute",
    top: 18,
    right: 26,
    width: 4,
    height: 12,
    borderRadius: 2,
    backgroundColor: "rgba(255,195,77,0.84)",
    transform: [{ rotate: "28deg" }],
  },
  profileBrandSparkTwo: {
    position: "absolute",
    top: 24,
    left: 26,
    width: 3,
    height: 10,
    borderRadius: 2,
    backgroundColor: "rgba(255,195,77,0.68)",
    transform: [{ rotate: "-26deg" }],
  },
  profileBrandSparkThree: {
    position: "absolute",
    top: 12,
    width: 3,
    height: 9,
    borderRadius: 2,
    backgroundColor: "rgba(255,195,77,0.58)",
  },
  profileDisplayName: {
    color: T.primary,
    fontSize: 30,
    lineHeight: 34,
    fontFamily: T.fontDisplayBold,
    textAlign: "center",
    marginTop: 0,
  },
  profileRolePill: {
    marginTop: 0,
    borderRadius: 999,
    backgroundColor: "rgba(255,195,77,0.94)",
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  profileRoleText: {
    color: T.textPrimary,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
    textTransform: "capitalize",
  },
  profileSectionTitle: {
    color: T.primary,
    fontSize: 17,
    fontFamily: T.fontBodyBold,
  },
  profileSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileSectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileSignalGrid: {
    flexDirection: "row",
    gap: 10,
  },
  profileSignalCard: {
    flex: 1,
    minHeight: 132,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(214,198,169,0.42)",
    backgroundColor: "rgba(255,252,247,0.94)",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 16,
    shadowColor: "#DBC6A7",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  profileSignalIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(233,236,206,0.58)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileSignalLabel: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  profileSignalValue: {
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  profileInfoRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(251,143,255,0.12)",
  },
  profileInfoRowLast: {
    borderBottomWidth: 0,
  },
  profileInfoLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 0,
  },
  profileInfoValueWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  profileInfoValue: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
    maxWidth: "88%",
  },
  profileNowSection: {
    gap: 10,
  },
  profilePresenceCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(214,198,169,0.42)",
    backgroundColor: "rgba(255,252,247,0.96)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  profilePresenceCopy: {
    flex: 1,
    gap: 12,
  },
  profilePresenceVenue: {
    color: T.textPrimary,
    fontSize: 19,
    lineHeight: 24,
    fontFamily: T.fontBodyMedium,
  },
  profilePresencePill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    backgroundColor: "rgba(233,236,206,0.72)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxWidth: "100%",
  },
  profilePresenceDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.visibilityOn,
  },
  profilePresencePillText: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
  },
  profileActivitySection: {
    gap: 10,
  },
  profileActivityCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(214,198,169,0.42)",
    backgroundColor: "rgba(255,252,247,0.96)",
    paddingVertical: 14,
    flexDirection: "row",
  },
  profileStatItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    borderRightWidth: 1,
    borderRightColor: "rgba(214,198,169,0.34)",
  },
  profileStatItemLast: {
    borderRightWidth: 0,
  },
  profileStatValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  profileStatValue: {
    color: T.textPrimary,
    fontSize: 24,
    lineHeight: 28,
    fontFamily: T.fontBodyBold,
  },
  profileStatLabel: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  profilePrivacyCard: {
    borderRadius: 24,
    backgroundColor: "rgba(255,248,236,0.9)",
    borderWidth: 1,
    borderColor: "rgba(214,198,169,0.34)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  profilePrivacyText: {
    flex: 1,
    color: T.textPrimary,
    fontSize: 15,
    lineHeight: 24,
    fontFamily: T.fontBody,
  },
  profilePrivacyIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(233,236,206,0.72)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileEditCard: {
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  profileEditActions: {
    gap: 10,
  },
  profileEditCancel: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profileEditCancelText: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
} as const;
