import { T } from "../../theme";

export const profileStyles = {
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  profileHeroBlock: {
    alignItems: "center",
    gap: 10,
    marginBottom: 28,
  },
  profileName: {
    color: T.textPrimary,
    fontSize: 28,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.6,
    textAlign: "center",
  },
  profileIntent: {
    color: T.textSecondary,
    fontSize: 14,
    textTransform: "capitalize",
  },
  chipWrapCenter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  profileSections: {
    gap: 4,
    marginBottom: 28,
  },
  profileActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  profileDestructive: {
    gap: 10,
    marginBottom: 20,
  },
  profileActionHint: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  reportPanel: {
    gap: 14,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    borderRadius: T.radiusLg,
    backgroundColor: T.dangerDim,
    padding: 16,
  },
  reportPanelTitle: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  reportPanelHint: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: -8,
  },
  reportChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mePage: {
    gap: 20,
  },
  meTopRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  profilePage: {
    gap: 20,
    paddingTop: 6,
  },
  profileTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileHeroEditButton: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 1,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  profileHeaderButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  profileEditHeaderButton: {
    minWidth: 58,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  profileEditHeaderText: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHeaderTitle: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHeroCard: {
    position: "relative",
    width: "100%",
    alignItems: "center",
    gap: 8,
    paddingTop: 2,
    paddingBottom: 4,
  },
  profileBrandHalo: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: T.surfaceCard,
    shadowColor: T.venueAccent,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
    position: "relative",
  },
  profileBrandCore: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: T.venueSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  profileDisplayName: {
    color: T.primary,
    fontSize: 28,
    lineHeight: 32,
    fontFamily: T.fontDisplayBold,
    textAlign: "center",
    marginTop: 0,
  },
  profileRolePill: {
    marginTop: 2,
    borderRadius: 999,
    backgroundColor: T.surfaceDim,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  profileRoleText: {
    color: T.textSecondary,
    fontSize: 13,
    fontFamily: T.fontBodyMedium,
    textTransform: "capitalize",
  },
  profileSectionTitle: {
    color: T.primary,
    fontSize: 17,
    fontFamily: T.fontBodyBold,
  },
  profileSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileSectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileSignalGrid: {
    flexDirection: "row",
    gap: 8,
  },
  profileSignalCard: {
    flex: 1,
    minHeight: 112,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 8,
    paddingVertical: 13,
    shadowColor: T.primary,
    shadowOpacity: 0.025,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  profileSignalIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.venueSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  profileSignalLabel: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  profileSignalValue: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  profileInfoRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(251,143,255,0.12)",
  },
  profileInfoRowLast: {
    borderBottomWidth: 0,
  },
  profileInfoLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 0,
  },
  profileInfoValueWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  profileInfoValue: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
    maxWidth: "88%",
  },
  profileNowSection: {
    gap: 0,
  },
  profilePresenceCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 14,
    shadowColor: T.primary,
    shadowOpacity: 0.03,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  profilePresenceTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  profilePresenceCopy: {
    flex: 1,
    minWidth: 0,
  },
  profilePresenceTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profilePresenceIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.visibilityOffSoft,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profilePresenceIconWrapVisible: {
    backgroundColor: T.visibilityOnSoft,
  },
  profilePresenceTitleCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  profilePresenceVenue: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  profilePresenceMessage: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  profilePresenceDivider: {
    height: 1,
    backgroundColor: T.border,
  },
  profilePresenceNotesRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  profilePresenceNote: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  profilePresenceDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.visibilityOff,
  },
  profilePresenceDotVisible: {
    backgroundColor: T.visibilityOn,
  },
  profilePresenceNoteText: {
    color: T.textSecondary,
    fontSize: 10,
    lineHeight: 13,
    fontFamily: T.fontBodyMedium,
    flexShrink: 1,
  },
  profilePresenceNoteSeparator: {
    color: T.textMuted,
    fontSize: 10,
  },
  profilePresencePrivacyNote: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  profilePresencePrivacyText: {
    color: T.textSecondary,
    fontSize: 9,
    lineHeight: 12,
    fontFamily: T.fontBodyMedium,
    maxWidth: 125,
    flexShrink: 1,
  },
  profileActivitySection: {
    gap: 10,
  },
  profileActivityCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingVertical: 12,
    flexDirection: "row",
  },
  profileStatItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    borderRightWidth: 1,
    borderRightColor: T.border,
  },
  profileStatItemLast: {
    borderRightWidth: 0,
  },
  profileStatValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  profileStatValue: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontFamily: T.fontBodyBold,
  },
  profileStatLabel: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  profileEditCard: {
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  profileEditActions: {
    gap: 10,
  },
  profileEditCancel: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profileEditCancelText: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
} as const;
