import { T } from "../../theme";

export const settingsStyles = {
  settingsPage: {
    gap: 18,
  },
  settingsTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsGroupTitle: {
    color: T.textPrimary,
    fontSize: 15,
    fontFamily: T.fontBodyBold,
    marginLeft: 2,
  },
  settingsMenuCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    overflow: "hidden",
    shadowColor: T.primary,
    shadowOpacity: 0.025,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  settingsMenuRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  settingsMenuRowLast: {
    borderBottomWidth: 0,
  },
  settingsMenuTextBlock: {
    flex: 1,
    gap: 3,
  },
  settingsMenuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: T.venueSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsMenuLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  settingsMenuHelper: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsMenuValue: {
    color: T.textSecondary,
    fontSize: 13,
  },
  settingsInputRow: {
    gap: 8,
  },
  settingsEditLabel: {
    color: T.textPrimary,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  settingsInlineInput: {
    borderWidth: 1,
    borderColor: T.borderBlack,
    borderRadius: 16,
    backgroundColor: T.surfaceDim,
    color: T.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  settingsActionSection: {
    gap: 10,
  },
  settingsActionHint: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 2,
  },
  settingsDangerCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    backgroundColor: T.surfaceCard,
    padding: 18,
    gap: 16,
  },
  settingsDangerHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  settingsDangerIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.dangerDim,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsDangerCopy: {
    flex: 1,
    gap: 4,
  },
  settingsDangerTitle: {
    color: T.dangerText,
    fontSize: 16,
    fontFamily: T.fontBodyBold,
  },
  settingsDangerBody: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: T.fontBody,
  },
  settingsRemovalStatus: {
    borderRadius: 16,
    backgroundColor: T.surfaceCard,
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  settingsRemovalStatusCopy: {
    flex: 1,
    gap: 2,
  },
  settingsRemovalStatusTitle: {
    color: T.visibilityOn,
    fontSize: 14,
    fontFamily: T.fontBodyBold,
  },
  settingsInfoBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsSuccessText: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
} as const;
