import { T } from "../../theme";

export const settingsStyles = {
  settingsPage: {
    gap: 22,
  },
  settingsTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsGroupTitle: {
    color: T.textPrimary,
    fontSize: 18,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    marginLeft: 4,
  },
  settingsMenuCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    overflow: "hidden",
  },
  settingsMenuRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(251,143,255,0.12)",
  },
  settingsMenuRowLast: {
    borderBottomWidth: 0,
  },
  settingsMenuTextBlock: {
    flex: 1,
    gap: 3,
  },
  settingsMenuLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  settingsMenuHelper: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsMenuValue: {
    color: T.textSecondary,
    fontSize: 13,
  },
  settingsEditCard: {
    gap: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  settingsInputRow: {
    gap: 8,
  },
  settingsEditLabel: {
    color: T.textPrimary,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  settingsInlineInput: {
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    borderRadius: 14,
    backgroundColor: "rgba(255,253,248,0.78)",
    color: T.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  settingsPromptInput: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  settingsVenueRow: {
    gap: 10,
    paddingTop: 6,
  },
  settingsLogoutButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: T.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  settingsLogoutText: {
    color: T.white,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  settingsHeader: {
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    marginBottom: 8,
  },
  settingsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsAvatarGlyph: {
    color: T.accentBright,
    fontSize: 28,
    fontWeight: "600",
  },
  settingsIdentity: {
    gap: 4,
    alignItems: "center",
  },
  settingsTitle: {
    color: T.textPrimary,
    fontSize: 26,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  settingsSubtitle: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  settingsActionStack: {
    gap: 12,
  },
  settingsInfoCard: {
    gap: 8,
    padding: 16,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
  },
  settingsInfoTitle: {
    color: T.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  settingsInfoBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsSuccessText: {
    color: T.accentBright,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsDangerStack: {
    gap: 10,
    marginTop: 4,
  },
} as const;
