import { StyleSheet } from "react-native";
import { T } from "../../theme";

export const venueRadarStyles = StyleSheet.create({
  page: {
    width: "100%",
    alignItems: "center",
    gap: 16,
  },
  titleBlock: {
    width: "100%",
    maxWidth: 390,
    gap: 12,
  },
  headerRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  statusActionPill: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    borderRadius: 999,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    paddingLeft: 4,
    paddingRight: 1,
    paddingVertical: 2,
    gap: 2,
  },
  compactStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 7,
    paddingRight: 8,
    paddingVertical: 6,
    borderRadius: 999,
  },
  compactStatusPillVisible: {
    backgroundColor: T.visibilityOnSoft,
  },
  compactStatusPillHidden: {
    backgroundColor: T.visibilityOffSoft,
  },
  compactStatusLabel: {
    color: T.textPrimary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  statusActionDivider: {
    width: 1,
    height: 20,
    backgroundColor: T.border,
    marginVertical: 0,
  },
  compactPrivacyButton: {
    width: 34,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroTitle: {
    flexShrink: 1,
    color: T.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.7,
  },
  heroSignalWrap: {
    marginTop: 2,
  },
  heroSubtitle: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    fontFamily: T.fontBody,
    maxWidth: 360,
  },
  insightRow: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
  },
  insightCard: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: T.surfaceCard,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 15,
    shadowColor: T.primary,
    shadowOpacity: 0.025,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
    gap: 10,
  },
  insightLabel: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: T.fontBodyMedium,
  },
  insightValueRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  insightIconBubble: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  insightIconBubbleEnergy: {
    backgroundColor: T.visibilityOnSoft,
  },
  insightIconBubbleBusy: {
    backgroundColor: T.visibilityOffSoft,
  },
  insightIconBubbleIntent: {
    backgroundColor: T.visibilityOffSoft,
  },
  insightTitle: {
    color: T.textPrimary,
    flex: 1,
    flexShrink: 1,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  insightSubtext: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  mapCard: {
    width: "100%",
    maxWidth: 390,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    padding: 8,
    shadowColor: T.primary,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  mapFrame: {
    width: "100%",
    height: 438,
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.primarySoft,
  },
  mapbox: {
    ...StyleSheet.absoluteFillObject,
  },
  mapFallback: {
    ...StyleSheet.absoluteFillObject,
  },
  mapWarmWash: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.2,
  },
  mapPatchOne: {
    position: "absolute",
    top: 52,
    left: 30,
    width: 120,
    height: 84,
    borderRadius: 26,
    backgroundColor: T.visibilityOffSoft,
    transform: [{ rotate: "-14deg" }],
  },
  mapPatchTwo: {
    position: "absolute",
    right: 34,
    top: 92,
    width: 102,
    height: 68,
    borderRadius: 24,
    backgroundColor: T.primarySoft,
  },
  mapPatchThree: {
    position: "absolute",
    right: 44,
    bottom: 76,
    width: 94,
    height: 94,
    borderRadius: 47,
    backgroundColor: T.primarySoft,
  },
  mapRoadHorizontal: {
    position: "absolute",
    left: -20,
    right: -20,
    top: 210,
    height: 26,
    borderRadius: 14,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
  },
  mapRoadVertical: {
    position: "absolute",
    top: 42,
    bottom: -20,
    left: 160,
    width: 24,
    borderRadius: 14,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
  },
  mapRoadDiagonal: {
    position: "absolute",
    left: 42,
    top: 132,
    width: 240,
    height: 22,
    borderRadius: 12,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    transform: [{ rotate: "32deg" }],
  },
  ringOuter: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: T.border,
  },
  ringMid: {
    position: "absolute",
    width: 204,
    height: 204,
    borderRadius: 102,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: T.border,
  },
  ringInner: {
    position: "absolute",
    width: 132,
    height: 132,
    borderRadius: 66,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: T.visibilityOffSoft,
  },
  ringInnerVisible: {
    borderColor: T.visibilityOnSoft,
  },
  centerVenueGlow: {
    position: "absolute",
    width: 146,
    height: 146,
    borderRadius: 73,
    backgroundColor: T.visibilityOffSoft,
  },
  centerVenueGlowVisible: {
    backgroundColor: T.visibilityOnSoft,
  },
  centerVenueBoundary: {
    position: "absolute",
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: T.visibilityOff,
    backgroundColor: T.visibilityOffSoft,
  },
  centerVenueBoundaryVisible: {
    borderColor: T.visibilityOn,
    backgroundColor: T.visibilityOnSoft,
  },
  venueMarker: {
    position: "absolute",
    width: 74,
    minHeight: 48,
    alignItems: "center",
  },
  venueMarkerHidden: {
    opacity: 0.78,
  },
  venueMarkerPin: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: T.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: T.primary,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 3 },
  },
  venueMarkerCopy: {
    marginTop: 6,
    alignItems: "center",
  },
  venueMarkerName: {
    color: T.textPrimary,
    fontSize: 10.5,
    lineHeight: 13,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  personPulse: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 2,
    borderColor: T.surfaceGlassStrong,
    shadowColor: T.primary,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  personPulseFeatured: {
    backgroundColor: T.primarySoft,
  },
  personPulseHalo: {
    position: "absolute",
    width: "100%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: T.primarySoft,
    borderWidth: 1,
    borderColor: T.border,
  },
  centerBadge: {
    position: "absolute",
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 2,
    borderColor: T.surfaceGlassStrong,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    shadowColor: T.primary,
    shadowOpacity: 0.04,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
  },
  centerBadgeSubtitle: {
    color: T.textSecondary,
    fontSize: 10,
    lineHeight: 12,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  currentVenueChip: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 22,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.border,
    shadowColor: T.primary,
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  currentVenuePin: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: T.venueSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  currentVenueCopy: {
    flex: 1,
    alignItems: "flex-start",
    gap: 1,
  },
  currentVenueChipText: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
  },
  currentVenueChipMeta: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  currentVenueArrowBubble: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.surfaceMid,
    borderWidth: 1,
    borderColor: T.border,
  },
  momentumCard: {
    width: "100%",
    maxWidth: 390,
    borderRadius: 22,
    backgroundColor: T.surfaceGlassStrong,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 10,
  },
  momentumHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  momentumEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontFamily: T.fontBodyBold,
  },
  momentumDismiss: {
    color: T.accentBright,
    fontSize: 13,
    fontFamily: T.fontBodyBold,
  },
  momentumTitle: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: T.fontDisplayBold,
  },
  momentumBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: T.fontBody,
  },
  momentumButton: {
    minHeight: 44,
    borderRadius: 15,
    backgroundColor: T.surfaceMid,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  momentumButtonLabel: {
    color: T.primary,
    fontSize: 15,
    fontFamily: T.fontBodyBold,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
});
