import { StyleSheet } from "react-native";
import { leftShadows } from "../../shadow";
import { T } from "../../theme";
import { radii, screenTypography, spacing } from "../../token";

export const venueDetailStyles = StyleSheet.create({
  page: {
    marginHorizontal: -20,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: T.ink,
  },
  hero: {
    height: 252,
    marginHorizontal: spacing[4],
    borderRadius: radii.xxl,
    borderWidth: 1,
    borderColor: T.border,
    overflow: "hidden",
    backgroundColor: T.primarySoft,
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  googlePhoto: { ...StyleSheet.absoluteFillObject, width: "100%", height: "100%" },
  photoLoading: {
    position: "absolute", right: 16, bottom: 16, width: 36, height: 36,
    borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: T.surfaceGlassStrong,
  },
  photoAttribution: {
    paddingHorizontal: spacing[5], paddingTop: 8, flexDirection: "row", flexWrap: "wrap",
    alignItems: "center", columnGap: 4,
  },
  photoAttributionText: { color: T.textSecondary, fontFamily: T.fontBody, fontSize: 12, lineHeight: 17 },
  photoAttributionLink: { minHeight: 44, justifyContent: "center" },
  heroBackButton: {
    position: "absolute",
    top: 12,
    left: 12,
  },
  heroSaveButton: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassStrong,
    alignItems: "center",
    justifyContent: "center",
    ...leftShadows.small,
  },
  heroSaveButtonActive: {
    backgroundColor: T.primary,
    borderColor: T.primary,
  },
  detailPressed: { opacity: 0.82 },
  heroStatusGlass: {
    position: "absolute",
    left: spacing[4],
    bottom: spacing[4],
  },
  heroStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  heroStatusText: {
    color: T.textPrimary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: T.fontBodyBold,
  },
  content: {
    paddingHorizontal: spacing[5],
    paddingTop: 18,
    gap: 20,
  },
  identityBlock: {
    gap: 5,
  },
  title: {
    color: T.textPrimary,
    fontSize: screenTypography.heroTitle,
    lineHeight: screenTypography.heroTitleLineHeight,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.9,
  },
  subtitle: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 22,
    fontFamily: T.fontBodyBold,
  },
  venuePracticalHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  venuePracticalCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    overflow: "hidden",
    ...leftShadows.small,
  },
  venuePracticalRow: {
    minHeight: 66,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  venuePracticalRowLast: { borderBottomWidth: 0 },
  venuePracticalIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: T.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  venuePracticalCopy: { flex: 1, minWidth: 0, gap: 2 },
  venuePracticalTitle: { color: T.textPrimary, fontSize: 13, lineHeight: 17, fontFamily: T.fontBodyBold },
  venuePracticalText: { color: T.textSecondary, fontSize: 13, lineHeight: 19, fontFamily: T.fontBody },
  venuePracticalUnavailable: { color: T.textMuted, fontSize: 13, lineHeight: 19, fontFamily: T.fontBody },
  venuePracticalActions: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  venuePracticalAction: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  venuePracticalActionText: { color: T.primary, fontSize: 13, lineHeight: 18, fontFamily: T.fontBodyBold },
  pulseCard: {
    minHeight: 84,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    ...leftShadows.small,
  },
  pulseIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  pulseCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pulseTitle: {
    fontSize: 16,
    lineHeight: 21,
    fontFamily: T.fontBodyBold,
  },
  pulseSubtitle: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  pulseBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
  },
  pulseBar: {
    width: 7,
    borderRadius: 4,
    borderWidth: 1,
  },
  pulseBarInactive: {
    backgroundColor: T.surfaceMid,
    borderColor: T.borderAccent,
  },
  peopleCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 10,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "stretch",
    ...leftShadows.small,
  },
  peopleHeading: {
    gap: 2,
  },
  peopleSubtitle: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
  peopleMetric: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 5,
  },
  peopleMetricDivider: {
    width: 1,
    backgroundColor: T.border,
  },
  peopleMetricValue: {
    color: T.textPrimary,
    fontSize: 24,
    lineHeight: 29,
    fontFamily: T.fontDisplayBold,
  },
  peopleMetricLabel: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  privacyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  privacyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.venueAccentSoft,
  },
  privacyCopy: {
    flex: 1,
    gap: 2,
  },
  privacyTitle: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: T.fontBodyBold,
  },
  privacyText: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: T.fontBody,
  },
});
