import { StyleSheet } from "react-native";

export const T = {
  ink: "#F7F4EE",
  inkSoft: "#FFFDF8",
  inkMid: "#EDE3D8",
  surface: "#FDF9F3",
  surfaceGlass: "rgba(247,244,238,0.72)",
  surfaceGlassStrong: "rgba(253,249,243,0.84)",
  surfaceGlassSoft: "rgba(247,244,238,0.58)",
  surfaceGlassUltra: "rgba(253,249,243,0.62)",
  surfaceGlassLilac: "rgba(134,22,47,0.28)",
  surfaceDim: "#F1E7DD",
  surfaceMid: "rgba(251,143,255,0.1)",
  surfaceCard: "#F4ECE3",
  accent: "#FB8FFF",
  accentDim: "rgba(251,143,255,0.16)",
  accentBright: "#5BCBFF",
  danger: "#B94A48",
  dangerDim: "rgba(185,74,72,0.12)",
  dangerBorder: "rgba(185,74,72,0.28)",
  dangerText: "#A63F3E",
  teal: "#1F78A1",
  tealDim: "rgba(31,120,161,0.18)",
  white: "#ffffff",
  textPrimary: "#171221",
  textSecondary: "rgba(23,18,33,0.7)",
  textMuted: "rgba(23,18,33,0.42)",
  borderBlack: "rgba(0,0,0,0.78)",
  borderBlackSoft: "rgba(0,0,0,0.58)",
  border: "rgba(251,143,255,0.16)",
  borderAccent: "rgba(251,143,255,0.36)",
  fontBody: "Manrope_400Regular",
  fontBodyMedium: "Manrope_500Medium",
  fontBodyBold: "Manrope_700Bold",
  fontDisplay: "Manrope_500Medium",
  fontDisplayBold: "Manrope_700Bold",
  fontDisplayLight: "Manrope_300Light",
  radiusXs: 10,
  radius: 20,
  radiusSm: 12,
  radiusLg: 24,
  radiusXl: 28,
};

const CONTENT_RAIL_WIDTH = "92%" as const;
const CONTENT_RAIL_MAX = 392;

export const styles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  shell: {
    flex: 1,
    backgroundColor: T.ink,
  },
  grain: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.02,
    backgroundColor: "transparent",
  },
  toast: {
    position: "absolute",
    left: 24,
    right: 24,
    bottom: 116,
    zIndex: 30,
    alignItems: "center",
  },
  toastText: {
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "rgba(31,28,36,0.94)",
    color: T.white,
    fontSize: 14,
    fontWeight: "700",
    paddingHorizontal: 18,
    paddingVertical: 12,
    textAlign: "center",
  },
  waveLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  waveTrack: {
    position: "absolute",
    left: -240,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  waveSegmentClip: {
    width: 180,
    height: 52,
    overflow: "hidden",
    marginLeft: -2,
  },
  waveSegment: {
    width: 180,
    height: 104,
    borderRadius: 52,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "transparent",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 72,
    gap: 0,
  },
  contentWithFooter: {
    paddingBottom: 246,
  },
  fullContent: {
    flex: 1,
    padding: 0,
  },
  loadingWrap: {
    flex: 1,
    minHeight: 700,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  loadingCenter: {
    alignItems: "center",
    gap: 16,
  },
  loadingLogo: {
    width: 118,
    height: 28,
  },
  loadingRing: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingChevron: {
    color: T.accent,
    fontSize: 44,
    fontWeight: "200",
    lineHeight: 52,
    marginRight: -6,
  },
  loadingDot: {
    position: "absolute",
    right: 28,
    top: 38,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: T.accent,
  },
  loadingWordmark: {
    color: T.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 5,
  },
  loadingCaption: {
    color: T.textMuted,
    fontSize: 14,
  },
  authWrap: {
    flex: 1,
    minHeight: 812,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  authGlowTop: {
    position: "absolute",
    top: -120,
    left: "15%",
    right: "15%",
    height: 400,
    borderRadius: 200,
    backgroundColor: "rgba(251,143,255,0.16)",
  },
  authGlowBottom: {
    position: "absolute",
    bottom: -80,
    left: "10%",
    right: "10%",
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(251,143,255,0.10)",
  },
  authBrand: {
    alignItems: "center",
    paddingTop: 100,
    gap: 12,
  },
  authMarkRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.24)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251,143,255,0.10)",
  },
  authMarkChevron: {
    color: T.accentBright,
    fontSize: 34,
    fontWeight: "200",
    lineHeight: 40,
    marginRight: -4,
  },
  authMarkDot: {
    position: "absolute",
    right: 17,
    top: 24,
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: T.accent,
  },
  authWordmarkWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authWordmarkRule: {
    width: 26,
    height: 1,
    backgroundColor: "rgba(251,143,255,0.28)",
  },
  authWordmark: {
    color: T.accentBright,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 4.2,
  },
  authCard: {
    marginHorizontal: 20,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surface,
    paddingHorizontal: 26,
    paddingTop: 32,
    paddingBottom: 36,
    overflow: "hidden",
  },
  authCardAccentLine: {
    position: "absolute",
    top: 0,
    left: 40,
    right: 40,
    height: 1,
    backgroundColor: T.accent,
    opacity: 0.6,
  },
  authHeadline: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "300",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    marginBottom: 14,
    textAlign: "center",
  },
  authSub: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 36,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  authBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.accent,
    borderRadius: 16,
    paddingVertical: 17,
    paddingHorizontal: 20,
  },
  authBtnPressed: {
    opacity: 0.85,
  },
  authBtnGIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  authBtnG: {
    color: T.white,
    fontSize: 14,
    fontWeight: "800",
  },
  authBtnLabel: {
    color: T.white,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  authFooter: {
    alignItems: "center",
    paddingBottom: 36,
    gap: 8,
  },
  authFooterLinks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authFooterLink: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterDivider: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterCopy: {
    color: "rgba(255,255,255,0.24)",
    fontSize: 11,
    letterSpacing: 3,
  },
  card: {
    gap: 20,
  },
  cardStepRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardStepText: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: T.fontBodyBold,
    letterSpacing: 2,
  },
  cardTitle: {
    color: T.textPrimary,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "400",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.2,
    textAlign: "center",
  },
  cardBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  avatarTile: {
    width: "47%",
    minHeight: 132,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 18,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 14,
  },
  avatarTileActive: {
    borderColor: T.borderAccent,
    backgroundColor: "rgba(251,143,255,0.12)",
  },
  avatarGlyph: {
    color: T.textSecondary,
    fontSize: 32,
    lineHeight: 38,
  },
  avatarGlyphActive: {
    color: T.textPrimary,
  },
  avatarTileLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  avatarTileLabelActive: {
    color: T.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radiusSm,
    backgroundColor: T.surfaceCard,
    color: T.textPrimary,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  multilineInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radius,
    padding: 16,
    gap: 16,
    backgroundColor: T.surfaceCard,
  },
  toggleTextWrap: {
    gap: 2,
    flex: 1,
  },
  toggleLabel: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "500",
  },
  toggleSub: {
    color: T.textSecondary,
    fontSize: 13,
  },
  fieldBlock: {
    gap: 12,
  },
  fieldLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.8,
  },
  infoBlock: {
    gap: 8,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  infoText: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
  },
  icebreakerText: {
    color: T.accentBright,
    fontStyle: "italic",
  },
  venuePage: {
    gap: 0,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  venuePageHeaderStack: {
    gap: 10,
    alignItems: "center",
    width: "100%",
  },
  venuePageBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 0,
    width: CONTENT_RAIL_WIDTH,
    maxWidth: CONTENT_RAIL_MAX,
  },
  venuePageTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    width: CONTENT_RAIL_WIDTH,
    maxWidth: CONTENT_RAIL_MAX,
  },
  venueHeaderUtilityBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251,143,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
  },
  venueHeaderUtilityIcon: {
    color: T.accentBright,
  },
  venueMainStack: {
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
    width: "100%",
  },
  venueRadarSection: {
    alignItems: "center",
    paddingTop: 2,
    paddingBottom: 2,
    width: "100%",
  },
  venuePageSupportStack: {
    gap: 0,
  },
  venueHeroCard: {
    borderRadius: T.radiusXl,
    borderWidth: 1,
    borderColor: T.borderBlack,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 22,
    overflow: "hidden",
    backgroundColor: T.surfaceGlassUltra,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.12,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  venueHeroCardRadar: {
    borderRadius: T.radiusXl,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 22,
    overflow: "hidden",
    backgroundColor: T.surfaceGlassStrong,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  venueHeroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 18,
  },
  venueHeroEyebrow: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2.4,
    textTransform: "uppercase",
  },
  venueHeroEyebrowRadar: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2.6,
    textTransform: "uppercase",
  },
  venueStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueStatusPillRadar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: "rgba(255,255,255,0.88)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  venueStatusDotActive: {
    backgroundColor: T.accent,
  },
  venueStatusDotRadar: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  venueStatusDotRadarActive: {
    backgroundColor: "#7dff8a",
  },
  venueStatusLabel: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  venueStatusLabelRadar: {
    color: T.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  venueHeaderRow: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  venueRadarHeader: {
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginBottom: 6,
  },
  venueHeaderCopy: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minWidth: 0,
    gap: 6,
    alignItems: "center",
  },
  venueHeaderCopyRadar: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  venueHeaderCopyRadarCentered: {
    minWidth: 0,
    gap: 6,
    alignItems: "center",
  },
  venueName: {
    color: T.accentBright,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
    textAlign: "center",
  },
  venueNameRadar: {
    color: T.textPrimary,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
  },
  venueVisibleCount: {
    color: T.textSecondary,
    fontSize: 15,
    fontWeight: "500",
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  venueVisibleCountRadar: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "500",
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  venuePulseCopy: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 260,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  venuePulseCopyRadarCentered: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 14,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  venueEnergyPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    flexShrink: 0,
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.accentDim,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  venueHeaderMetaStack: {
    alignItems: "flex-end",
    gap: 10,
  },
  venueEnergyPillRadar: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(226,150,123,0.34)",
    backgroundColor: "rgba(226,150,123,0.12)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  venueEnergyIcon: {
    color: T.accentBright,
    fontSize: 14,
    fontWeight: "800",
  },
  venueEnergyIconRadar: {
    color: "#ff9bd9",
    fontSize: 14,
    fontWeight: "800",
  },
  venueEnergyLabel: {
    color: T.accentBright,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.2,
  },
  venueEnergyLabelRadar: {
    color: "#ffd5ef",
    fontSize: 12,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.2,
  },
  venueIntentBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueIntentBadgeLabel: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 12,
    fontWeight: "700",
  },
  venueStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  venueStatCard: {
    flex: 1,
    minHeight: 78,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassLilac,
    paddingHorizontal: 14,
    paddingVertical: 14,
    justifyContent: "space-between",
    gap: 10,
  },
  venueStatValue: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    letterSpacing: -0.4,
  },
  venueStatLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  venueRadarStage: {
    width: 264,
    height: 264,
    alignSelf: "center",
    marginTop: -6,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  venueRadarStagePrivate: {
    height: 264,
  },
  venueRadarSweepWrap: {
    position: "absolute",
    width: 264,
    height: 264,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  venueRadarSweep: {
    position: "absolute",
    top: 10,
    width: 2,
    height: 122,
    borderRadius: 999,
    backgroundColor: "rgba(251,143,255,0.18)",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarChargeRing: {
    position: "absolute",
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: "rgba(251,143,255,0.34)",
    backgroundColor: "rgba(251,143,255,0.06)",
  },
  venueRadarChargeRingSecondary: {
    position: "absolute",
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "rgba(251,143,255,0.26)",
  },
  venueRadarGlow: {
    position: "absolute",
    width: 224,
    height: 224,
    borderRadius: 112,
    backgroundColor: "rgba(251,143,255,0.10)",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarAuraOuter: {
    position: "absolute",
    width: 236,
    height: 236,
    borderRadius: 118,
    borderWidth: 7,
    borderColor: "rgba(251,143,255,0.08)",
  },
  venueRadarAuraInner: {
    position: "absolute",
    width: 182,
    height: 182,
    borderRadius: 91,
    borderWidth: 4,
    borderColor: "rgba(251,143,255,0.07)",
  },
  venueRadarRingOuter: {
    position: "absolute",
    width: 208,
    height: 208,
    borderRadius: 104,
    borderWidth: 3,
    borderColor: "rgba(251,143,255,0.42)",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarRingMid: {
    position: "absolute",
    width: 152,
    height: 152,
    borderRadius: 76,
    borderWidth: 2,
    borderColor: "rgba(251,143,255,0.28)",
  },
  venueRadarRingInner: {
    position: "absolute",
    width: 104,
    height: 104,
    borderRadius: 52,
    borderWidth: 2,
    borderColor: "rgba(251,143,255,0.22)",
  },
  venueRadarPing: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarPingPulse: {
    position: "absolute",
    width: "100%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(251,143,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.24)",
  },
  venueRadarPingFeatured: {
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarPingMuted: {
    opacity: 0.84,
  },
  venueRadarPingRing: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    padding: 2,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  venueRadarPingInner: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: T.inkSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
  },
  venueRadarPingGlyph: {
    color: T.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  venueRadarSignalDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "rgba(251,143,255,0.22)",
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
  },
  venueRadarSignalDotA: {
    top: 78,
    left: 188,
  },
  venueRadarSignalDotB: {
    top: 112,
    left: 198,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  venueRadarSignalDotC: {
    top: 214,
    left: 60,
  },
  venueRadarPingPresenceSoft: {
    position: "absolute",
    right: 1,
    bottom: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FB8FFF",
    borderWidth: 1.5,
    borderColor: T.white,
  },
  venueRadarCountBadge: {
    position: "absolute",
    top: 78,
    left: 68,
    minWidth: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarCountBadgeLabel: {
    color: T.white,
    fontSize: 18,
    fontWeight: "800",
  },
  venueRadarCenterWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarCenterRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    padding: 3,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarCenterCore: {
    flex: 1,
    borderRadius: 41,
    backgroundColor: T.inkSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    overflow: "hidden",
  },
  venueRadarCenterHalo: {
    position: "absolute",
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(251,143,255,0.10)",
  },
  venueRadarCenterLogoWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginRight: -2,
  },
  venueRadarCenterLogoChevron: {
    color: T.white,
    fontSize: 44,
    lineHeight: 44,
    fontWeight: "300",
  },
  venueRadarCenterLogoDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: T.white,
  },
  venueRadarBeaconOuter: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "rgba(251,143,255,0.32)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarBeaconMid: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "rgba(251,143,255,0.62)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarBeaconDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: T.accentBright,
  },
  venueRadarCaptionBlock: {
    alignItems: "center",
    gap: 6,
    marginTop: -6,
  },
  venueRadarCaptionBlockPrivate: {
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  venueRadarCenterLabel: {
    color: T.textPrimary,
    fontSize: 16,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.2,
    textAlign: "center",
  },
  venueRadarCenterCaption: {
    color: T.textSecondary,
    fontSize: 13,
    textAlign: "center",
    maxWidth: 220,
    lineHeight: 19,
  },
  venueRadarInfoRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  venuePrivateHelperText: {
    marginTop: 0,
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    maxWidth: 286,
  },
  venuePrivateStateStack: {
    alignItems: "center",
    gap: 12,
    width: CONTENT_RAIL_WIDTH,
    maxWidth: CONTENT_RAIL_MAX,
  },
  venueNearbyCard: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 12,
    marginTop: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.2)",
    backgroundColor: "rgba(253,249,243,0.84)",
    width: "100%",
  },
  venueNearbyCardIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251,143,255,0.12)",
  },
  venueNearbyCardIcon: {
    color: T.accentBright,
  },
  venueNearbyCardCopy: {
    flex: 1,
    gap: 1,
  },
  venueNearbyCardTitle: {
    color: T.accentBright,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBodyMedium,
    fontWeight: "600",
  },
  venueNearbyCardBody: {
    color: T.textSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  venueNearbyCardLockWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251,143,255,0.10)",
  },
  venueNearbyCardLock: {
    color: T.accentBright,
  },
  venueRadarInfoPill: {
    flex: 1,
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 6,
    alignItems: "center",
  },
  venueRadarInfoLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
  },
  venueRadarInfoValue: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  venueVibesSectionRadar: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginTop: 16,
  },
  venueVibeChipRadar: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueVibeChipRadarText: {
    color: T.accentBright,
    fontSize: 12,
    fontWeight: "700",
  },
  venueRadarEmptyCard: {
    width: 240,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 8,
    alignItems: "center",
  },
  venueRadarEmptyTitle: {
    color: T.textPrimary,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  venueRadarEmptyBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  venueClusterArea: {
    height: 520,
    justifyContent: "flex-end",
    paddingBottom: 118,
    position: "relative",
  },
  venueClusterAreaPrivate: {
    height: 360,
    paddingBottom: 64,
  },
  venueClusterGlow: {
    position: "absolute",
    top: 154,
    left: 118,
    width: 138,
    height: 138,
    borderRadius: 69,
    backgroundColor: "rgba(251,143,255,0.14)",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.6,
    shadowRadius: 44,
    shadowOffset: { width: 0, height: 0 },
  },
  venueBubble: {
    position: "absolute",
    borderWidth: 1,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  venueBubbleStandard: {
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
  },
  venueBubbleFeatured: {
    borderColor: T.accent,
    borderWidth: 6,
    backgroundColor: "#f1ebff",
    shadowOpacity: 0.55,
    shadowRadius: 28,
  },
  venueBubblePressed: {
    transform: [{ scale: 0.97 }],
  },
  venueBubbleInner: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  venueBubbleGlyph: {
    color: T.accentBright,
    fontSize: 26,
    fontWeight: "700",
  },
  venueBubbleGlyphFeatured: {
    color: T.textPrimary,
    fontSize: 36,
  },
  venueCountBubble: {
    position: "absolute",
    top: 74,
    left: 66,
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassUltra,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  venueCountBubbleLabel: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  venueClusterHint: {
    alignSelf: "center",
    color: T.textMuted,
    textTransform: "uppercase",
    fontSize: 13,
    letterSpacing: 3.2,
  },
  venueEmptyClusterCard: {
    marginTop: 132,
    marginHorizontal: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassUltra,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 8,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  venueEmptyClusterTitle: {
    color: T.textPrimary,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  venueEmptyClusterBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  venueVibesSection: {
    gap: 16,
  },
  venueSectionLabel: {
    color: T.textPrimary,
    fontSize: 18,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
  },
  venueSectionLabelRadar: {
    color: T.white,
    fontSize: 18,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
  },
  venueVibesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  venueVibePill: {
    minWidth: 166,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  venueVibePillPrimary: {
    borderColor: T.borderAccent,
    backgroundColor: "rgba(251,143,255,0.12)",
  },
  venueVibePillSecondary: {
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
  },
  venueVibePillMuted: {
    minWidth: 166,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: "rgba(31,120,161,0.16)",
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  venueVibeDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  venueVibeDotPrimary: {
    backgroundColor: T.accent,
  },
  venueVibeDotSecondary: {
    backgroundColor: T.accentBright,
  },
  venueVibeText: {
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: -0.3,
  },
  venueVibeTextPrimary: {
    color: T.accentBright,
  },
  venueVibeTextSecondary: {
    color: T.textPrimary,
  },
  venueVibeTextMuted: {
    color: T.textMuted,
    fontSize: 16,
    fontWeight: "500",
  },
  venuePreviewSection: {
    marginTop: 24,
    gap: 14,
  },
  venuePreviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  venuePreviewLink: {
    color: "#ffc2e8",
    fontSize: 13,
    fontWeight: "700",
  },
  venuePreviewList: {
    gap: 10,
  },
  venuePreviewCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  venuePreviewCardPressed: {
    borderColor: "rgba(255,176,228,0.4)",
    backgroundColor: "rgba(255,176,228,0.12)",
  },
  venuePreviewAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,176,228,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,176,228,0.34)",
    alignItems: "center",
    justifyContent: "center",
  },
  venuePreviewAvatarGlyph: {
    color: T.white,
    fontSize: 16,
    fontWeight: "700",
  },
  venuePreviewCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  venuePreviewName: {
    color: T.white,
    fontSize: 15,
    fontWeight: "600",
  },
  venuePreviewMeta: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 13,
  },
  venuePreviewTime: {
    color: "rgba(255,255,255,0.44)",
    fontSize: 12,
    fontWeight: "700",
  },
  momentumCard: {
    marginTop: 8,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: "rgba(255,255,255,0.76)",
    padding: 18,
    gap: 10,
  },
  momentumHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  momentumEyebrow: {
    color: "#ffc2e8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  momentumDismiss: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  momentumTitle: {
    color: T.textPrimary,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "600",
    letterSpacing: -0.4,
  },
  momentumBody: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  momentumActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  momentumPrimaryButton: {
    borderRadius: 999,
    backgroundColor: "#FB8FFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  momentumPrimaryLabel: {
    color: "#24182d",
    fontSize: 13,
    fontWeight: "700",
  },
  momentumGhostButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  momentumGhostLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "700",
  },
  venueActions: {
    marginTop: 8,
    alignItems: "center",
    width: "84%",
    maxWidth: 360,
    alignSelf: "center",
  },
  venuePrimaryAction: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: T.accent,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
    width: "100%",
  },
  venuePrimaryActionLabel: {
    color: T.white,
    fontSize: 15,
    lineHeight: 18,
    fontFamily: T.fontBodyBold,
    fontWeight: "800",
  },
  venuePrivacyNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    alignSelf: "center",
    gap: 6,
    marginTop: 12,
    marginBottom: 0,
    paddingHorizontal: 0,
    width: "100%",
    maxWidth: CONTENT_RAIL_MAX,
  },
  venuePrivacyNoteIcon: {
    color: T.accentBright,
    marginTop: 1,
  },
  venuePrivacyNoteText: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    textAlign: "left",
    flexShrink: 1,
  },
  venueChoiceList: {
    gap: 10,
  },
  pulseDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  pulseDotActive: {
    backgroundColor: T.teal,
  },
  visibleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  visibleBadgeLabel: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  energyPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  energyPillHigh: {
    borderColor: "rgba(62,207,178,0.3)",
    backgroundColor: T.tealDim,
  },
  energyPillLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  energyPillLabelHigh: {
    color: T.teal,
  },
  feedHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  feedHeadVenue: {
    color: T.textPrimary,
    fontSize: 22,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  feedHeadCount: {
    color: T.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  feedCard: {
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    borderRadius: T.radius,
    padding: 18,
    gap: 14,
    marginBottom: 14,
    backgroundColor: T.surfaceGlassLilac,
  },
  feedCardPressed: {
    backgroundColor: T.accentDim,
    borderColor: T.borderAccent,
  },
  feedCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedAvatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  feedAvatarGlyph: {
    color: T.accentBright,
    fontSize: 16,
    fontWeight: "600",
  },
  feedCardInfo: {
    flex: 1,
    gap: 2,
  },
  feedCardName: {
    color: T.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  feedCardIntent: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
  },
  feedCardTime: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  feedCardHint: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  feedCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 80,
    gap: 12,
  },
  emptyGlyph: {
    color: T.textMuted,
    fontSize: 48,
    fontWeight: "200",
  },
  emptyText: {
    color: T.textMuted,
    fontSize: 15,
  },
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  profileHeroBlock: {
    alignItems: "center",
    gap: 10,
    marginBottom: 28,
  },
  profileAvatarLg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  profileAvatarGlyph: {
    color: T.accentBright,
    fontSize: 30,
    fontWeight: "500",
  },
  profileName: {
    color: T.textPrimary,
    fontSize: 28,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.6,
    textAlign: "center",
  },
  profileIntent: {
    color: T.textSecondary,
    fontSize: 14,
    textTransform: "capitalize",
  },
  chipWrapCenter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  profileSections: {
    gap: 4,
    marginBottom: 28,
  },
  profileActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  profileDestructive: {
    gap: 10,
    marginBottom: 20,
  },
  profileActionHint: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  reportPanel: {
    gap: 14,
    borderWidth: 1,
    borderColor: T.dangerBorder,
    borderRadius: T.radiusLg,
    backgroundColor: T.dangerDim,
    padding: 16,
  },
  reportPanelTitle: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  reportPanelHint: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: -8,
  },
  reportChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  leftAvatarRingLg: {
    width: 122,
    height: 122,
    borderRadius: 61,
    borderWidth: 3,
    borderColor: T.white,
    backgroundColor: "rgba(251,143,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  leftAvatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FB8FFF",
    overflow: "hidden",
  },
  leftAvatarCircleSm: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  leftAvatarCircleLg: {
    width: 108,
    height: 108,
    borderRadius: 54,
  },
  leftAvatarCircleAbstract: {
    backgroundColor: "#86162F",
  },
  leftAvatarCircleMinimal: {
    backgroundColor: "#F8F1EA",
    borderWidth: 2,
    borderColor: "#FB8FFF",
  },
  leftAvatarCircleSoft: {
    backgroundColor: "#FB8FFF",
  },
  leftAvatarGlyphMark: {
    position: "absolute",
    color: "rgba(255,255,255,0.22)",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
  },
  leftAvatarGlyphMarkSm: {
    fontSize: 24,
    lineHeight: 28,
  },
  leftAvatarGlyphMarkLg: {
    fontSize: 58,
    lineHeight: 64,
  },
  leftAvatarText: {
    color: T.white,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: T.fontDisplayBold,
    zIndex: 1,
  },
  leftAvatarTextSm: {
    fontSize: 15,
    lineHeight: 20,
  },
  leftAvatarTextLg: {
    fontSize: 34,
    lineHeight: 40,
  },
  leftAvatarTextMinimal: {
    color: "#FB8FFF",
  },
  mePage: {
    gap: 20,
  },
  meTopRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  profilePage: {
    gap: 22,
    paddingTop: 0,
  },
  profileTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileHeaderButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  profileEditHeaderButton: {
    minWidth: 58,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  profileEditHeaderText: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHeaderTitle: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileHero: {
    alignItems: "center",
    gap: 8,
  },
  profileAvatarRing: {
    width: 122,
    height: 122,
    borderRadius: 61,
    borderWidth: 3,
    borderColor: T.white,
    backgroundColor: "rgba(251,143,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  profileAvatarCircle: {
    width: 108,
    height: 108,
    borderRadius: 54,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FB8FFF",
    overflow: "hidden",
  },
  profileAvatarCircleAbstract: {
    backgroundColor: "#86162F",
  },
  profileAvatarCircleMinimal: {
    backgroundColor: "#F8F1EA",
    borderWidth: 2,
    borderColor: "#FB8FFF",
  },
  profileAvatarCircleSoft: {
    backgroundColor: "#FB8FFF",
  },
  profileAvatarGlyphMark: {
    position: "absolute",
    color: "rgba(255,255,255,0.22)",
    fontSize: 58,
    fontWeight: "800",
    lineHeight: 64,
  },
  profileAvatarText: {
    color: T.white,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "800",
    fontFamily: T.fontDisplayBold,
    zIndex: 1,
  },
  profileAvatarTextMinimal: {
    color: "#FB8FFF",
  },
  profileDisplayName: {
    color: T.textPrimary,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    textAlign: "center",
    marginTop: 6,
  },
  profileEmail: {
    color: T.textSecondary,
    fontSize: 14,
    textAlign: "center",
  },
  profileRolePill: {
    marginTop: 4,
    borderRadius: 999,
    backgroundColor: "#FB8FFF",
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  profileRoleText: {
    color: T.white,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  profileSectionTitle: {
    color: T.textPrimary,
    fontSize: 17,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  profileInfoCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    overflow: "hidden",
  },
  profileInfoRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(251,143,255,0.12)",
  },
  profileInfoRowLast: {
    borderBottomWidth: 0,
  },
  profileInfoLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 0,
  },
  profileInfoValueWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  profileInfoValue: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
    maxWidth: "88%",
  },
  profileAboutBlock: {
    gap: 10,
  },
  profileAboutRule: {
    height: 1,
    backgroundColor: "rgba(251,143,255,0.14)",
    marginLeft: 6,
    marginRight: 40,
  },
  profileAboutText: {
    color: T.textPrimary,
    fontSize: 14,
    lineHeight: 21,
    paddingHorizontal: 6,
  },
  profileEditCard: {
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  profileEditActions: {
    gap: 10,
  },
  profileEditCancel: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  profileEditCancelText: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  homePage: {
    gap: 20,
    paddingTop: 4,
  },
  homeGreetingBlock: {
    gap: 4,
  },
  homeGreetingLabel: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "600",
    fontFamily: T.fontBodyBold,
  },
  homeGreetingName: {
    color: T.textPrimary,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "800",
    fontFamily: T.fontDisplayBold,
  },
  homeHeroCard: {
    borderRadius: 18,
    overflow: "hidden",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  homeHeroGradient: {
    minHeight: 132,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    paddingVertical: 18,
    overflow: "hidden",
  },
  homeHeroCopy: {
    width: "56%",
    gap: 0,
  },
  homeQuoteMark: {
    color: T.white,
    fontSize: 42,
    lineHeight: 32,
    fontWeight: "800",
  },
  homeHeroText: {
    color: T.white,
    fontSize: 18,
    lineHeight: 25,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  homeHeroPeople: {
    flex: 1,
    minHeight: 86,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    gap: -8,
    opacity: 0.96,
  },
  homeHeroStar: {
    position: "absolute",
    right: -2,
    top: 8,
  },
  homeSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  homeSectionTitle: {
    color: T.textPrimary,
    fontSize: 17,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  homeSectionAction: {
    color: T.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  homeEventList: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.18)",
    backgroundColor: "rgba(255,253,248,0.78)",
    overflow: "hidden",
  },
  homeEventRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(251,143,255,0.14)",
  },
  homeEventRowFirst: {
    borderTopWidth: 0,
  },
  homeEventIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  homeIconShine: {
    position: "absolute",
    top: 7,
    left: 8,
    width: 18,
    height: 8,
    borderRadius: 99,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  homeEventCopy: {
    flex: 1,
    gap: 2,
  },
  homeEventTitle: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  homeEventMeta: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  homeEventPlace: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  homeQuickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  homeQuickTile: {
    width: "48%",
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.86)",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  homeQuickIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#86162F",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  homeQuickLabel: {
    color: T.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    flexShrink: 1,
  },
  homeBecomeButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: T.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  homeBecomeButtonText: {
    color: T.white,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonPressed: {
    opacity: 0.82,
  },
  settingsPage: {
    gap: 22,
  },
  settingsTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsGroupTitle: {
    color: T.textPrimary,
    fontSize: 18,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    marginLeft: 4,
  },
  settingsMenuCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    overflow: "hidden",
  },
  settingsMenuRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(251,143,255,0.12)",
  },
  settingsMenuRowLast: {
    borderBottomWidth: 0,
  },
  settingsMenuTextBlock: {
    flex: 1,
    gap: 3,
  },
  settingsMenuLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  settingsMenuHelper: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsMenuValue: {
    color: T.textSecondary,
    fontSize: 13,
  },
  settingsEditCard: {
    gap: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  settingsInputRow: {
    gap: 8,
  },
  settingsEditLabel: {
    color: T.textPrimary,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  settingsInlineInput: {
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    borderRadius: 14,
    backgroundColor: "rgba(255,253,248,0.78)",
    color: T.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  settingsPromptInput: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  settingsVenueRow: {
    gap: 10,
    paddingTop: 6,
  },
  settingsLogoutButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: T.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  settingsLogoutText: {
    color: T.white,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
  },
  settingsHeader: {
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    marginBottom: 8,
  },
  settingsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsAvatarGlyph: {
    color: T.accentBright,
    fontSize: 28,
    fontWeight: "600",
  },
  settingsIdentity: {
    gap: 4,
    alignItems: "center",
  },
  settingsTitle: {
    color: T.textPrimary,
    fontSize: 26,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  settingsSubtitle: {
    color: T.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  settingsActionStack: {
    gap: 12,
  },
  settingsInfoCard: {
    gap: 8,
    padding: 16,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
  },
  settingsInfoTitle: {
    color: T.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  settingsInfoBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsSuccessText: {
    color: T.accentBright,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsDangerStack: {
    gap: 10,
    marginTop: 4,
  },
  adminPage: {
    gap: 18,
  },
  adminHeader: {
    gap: 12,
  },
  adminSubmissionList: {
    gap: 10,
  },
  adminDetailGrid: {
    gap: 16,
  },
  adminCandidateCard: {
    gap: 8,
    padding: 14,
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
  feedbackPromptOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(251,143,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 30,
  },
  feedbackPromptCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderBlack,
    backgroundColor: T.surface,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 18,
    gap: 16,
  },
  feedbackPromptEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  feedbackPromptTitle: {
    color: T.textPrimary,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "300",
    fontFamily: T.fontDisplay,
    letterSpacing: -1,
    textAlign: "center",
  },
  feedbackPromptBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  feedbackPromptBlock: {
    gap: 10,
  },
  feedbackPromptChoiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  feedbackPromptIcebreaker: {
    color: T.accentBright,
    fontSize: 14,
    lineHeight: 20,
    fontStyle: "italic",
  },
  feedbackPromptActions: {
    gap: 10,
  },
  feedbackPromptHint: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  safetyPage: {
    gap: 16,
  },
  safetyHeader: {
    gap: 8,
    marginTop: 8,
  },
  safetySectionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.16)",
    backgroundColor: "rgba(255,253,248,0.78)",
    padding: 16,
  },
  safetyStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  safetyStatusText: {
    color: T.textSecondary,
    fontSize: 14,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: T.tealDim,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: T.borderAccent,
  },
  chipSubtle: {
    backgroundColor: T.surfaceCard,
    borderColor: T.border,
  },
  chipLabel: {
    color: T.teal,
    fontSize: 12,
    fontWeight: "600",
  },
  chipLabelSubtle: {
    color: T.textSecondary,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  selectChip: {
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "transparent",
  },
  selectChipActive: {
    borderColor: T.accent,
    backgroundColor: T.accentDim,
  },
  selectChipLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  selectChipLabelActive: {
    color: T.accentBright,
    fontWeight: "600",
  },
  primaryBtn: {
    minHeight: 52,
    backgroundColor: T.accent,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  primaryBtnPressed: {
    opacity: 0.85,
  },
  primaryBtnDisabled: {
    backgroundColor: "rgba(251,143,255,0.35)",
  },
  primaryBtnLabel: {
    color: T.white,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: -0.1,
  },
  primaryBtnLabelDisabled: {
    color: "rgba(23,18,33,0.72)",
  },
  ghostBtn: {
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  ghostBtnCompact: {
    minHeight: 40,
    borderRadius: 14,
    flex: 0,
    paddingVertical: 9,
    paddingHorizontal: 14,
  },
  ghostBtnDestructive: {
    borderColor: T.dangerBorder,
    backgroundColor: T.dangerDim,
  },
  ghostBtnDisabled: {
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  ghostBtnLabel: {
    color: T.textSecondary,
    fontSize: 15,
    fontWeight: "700",
  },
  ghostBtnLabelDestructive: {
    color: T.dangerText,
  },
  ghostBtnLabelDisabled: {
    color: "rgba(23,18,33,0.42)",
  },
  backNavButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingRight: 12,
    paddingVertical: 4,
  },
  backNavButtonPressed: {
    opacity: 0.8,
  },
  backNavIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  backNavIcon: {
    color: T.accent,
    fontSize: 22,
    fontWeight: "200",
    lineHeight: 26,
    marginRight: -3,
  },
  backNavDot: {
    position: "absolute",
    right: 10,
    top: 14,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: T.accent,
  },
  backNavLabel: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  footerShell: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 10,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  footerSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: T.radius,
    backgroundColor: T.surface,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
  },
  footerPrivateRow: {
    marginBottom: 10,
    alignItems: "center",
  },
  footerPrivateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: T.radiusLg,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassStrong,
  },
  footerPrivateDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.accent,
  },
  footerPrivateText: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  footerVenueBlock: {
    flex: 1,
    gap: 3,
  },
  footerVenueLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  footerVenueName: {
    color: T.accentBright,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  footerSessionMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: T.radiusLg,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    maxWidth: "58%",
  },
  footerPresenceDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  footerPresenceDotActive: {
    backgroundColor: T.teal,
  },
  footerSessionText: {
    color: T.textPrimary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  footerNavRow: {
    position: "relative",
    minHeight: 88,
    marginTop: 0,
    paddingHorizontal: 4,
    paddingTop: 6,
    paddingBottom: 6,
    overflow: "visible",
  },
  footerNavTrack: {
    position: "relative",
    alignSelf: "center",
    width: CONTENT_RAIL_WIDTH,
    maxWidth: CONTENT_RAIL_MAX,
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 7,
    paddingBottom: 3,
    borderRadius: 24,
    backgroundColor: "rgba(253,249,243,0.92)",
    borderWidth: 1,
    borderColor: "rgba(251,143,255,0.12)",
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  footerNavBubbleTrack: {
    position: "absolute",
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 0,
  },
  footerNavMound: {
    position: "absolute",
    top: -16,
    width: 76,
    height: 28,
    borderTopLeftRadius: 38,
    borderTopRightRadius: 38,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: T.surface,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: T.borderBlack,
  },
  footerNavItem: {
    flex: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 3,
    zIndex: 1,
  },
  footerNavItemActive: {
    zIndex: 2,
  },
  footerNavItemPressed: {
    opacity: 0.86,
  },
  footerNavIconBubble: {
    width: 34,
    height: 34,
    borderRadius: T.radius,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNavIconPlaceholder: {
    width: 34,
    height: 34,
  },
  footerNavIconBubbleActive: {
    width: 38,
    height: 38,
    borderRadius: T.radius,
    backgroundColor: T.accent,
    shadowColor: "#FB8FFF",
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    marginTop: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNavIcon: {
    color: T.textMuted,
    fontSize: 22,
    lineHeight: 24,
  },
  footerNavIconActive: {
    color: T.accentBright,
  },
  footerNavLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.2,
    width: "100%",
    textAlign: "center",
  },
  footerNavLabelActive: {
    color: T.accentBright,
  },
  errorText: {
    color: "#ff8080",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
});
