import { StyleSheet } from "react-native";

export const T = {
  ink: "#0d0c10",
  inkSoft: "#1a1820",
  inkMid: "#2e2b38",
  surface: "#f4f2ee",
  surfaceDim: "#e8e5df",
  surfaceMid: "rgba(244,242,238,0.06)",
  surfaceCard: "rgba(244,242,238,0.05)",
  accent: "#7c6cf5",
  accentDim: "rgba(124,108,245,0.18)",
  accentBright: "#9f94ff",
  teal: "#3ecfb2",
  tealDim: "rgba(62,207,178,0.12)",
  white: "#ffffff",
  textPrimary: "#f4f2ee",
  textSecondary: "rgba(244,242,238,0.52)",
  textMuted: "rgba(244,242,238,0.28)",
  border: "rgba(244,242,238,0.09)",
  borderAccent: "rgba(124,108,245,0.4)",
  radius: 20,
  radiusSm: 12,
  radiusXl: 28,
};

export const styles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  shell: {
    flex: 1,
    backgroundColor: T.ink,
  },
  grain: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.03,
    backgroundColor: "transparent",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 72,
    gap: 0,
  },
  contentWithFooter: {
    paddingBottom: 190,
  },
  fullContent: {
    flex: 1,
    padding: 0,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 28,
  },
  wordmark: {
    color: T.textPrimary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 4,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: T.teal,
  },
  loadingWrap: {
    flex: 1,
    minHeight: 700,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  loadingCenter: {
    alignItems: "center",
    gap: 16,
  },
  loadingRing: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingChevron: {
    color: T.accent,
    fontSize: 44,
    fontWeight: "200",
    lineHeight: 52,
    marginRight: -6,
  },
  loadingDot: {
    position: "absolute",
    right: 28,
    top: 38,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: T.accent,
  },
  loadingWordmark: {
    color: T.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 5,
  },
  loadingCaption: {
    color: T.textMuted,
    fontSize: 14,
  },
  authWrap: {
    flex: 1,
    minHeight: 812,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  authGlowTop: {
    position: "absolute",
    top: -120,
    left: "15%",
    right: "15%",
    height: 400,
    borderRadius: 200,
    backgroundColor: "rgba(100,86,240,0.15)",
  },
  authGlowBottom: {
    position: "absolute",
    bottom: -80,
    left: "10%",
    right: "10%",
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(62,207,178,0.08)",
  },
  authBrand: {
    alignItems: "center",
    paddingTop: 100,
    gap: 14,
  },
  authMarkRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: "rgba(124,108,245,0.3)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(124,108,245,0.08)",
  },
  authMarkChevron: {
    color: T.accentBright,
    fontSize: 34,
    fontWeight: "200",
    lineHeight: 40,
    marginRight: -4,
  },
  authMarkDot: {
    position: "absolute",
    right: 17,
    top: 24,
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: T.accent,
  },
  authMarkLabel: {
    color: T.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 4,
  },
  authCard: {
    marginHorizontal: 20,
    borderRadius: T.radiusXl,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 26,
    paddingTop: 32,
    paddingBottom: 36,
    overflow: "hidden",
  },
  authCardAccentLine: {
    position: "absolute",
    top: 0,
    left: 40,
    right: 40,
    height: 1,
    backgroundColor: T.accent,
    opacity: 0.6,
  },
  authHeadline: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "300",
    letterSpacing: -1.5,
    marginBottom: 14,
  },
  authSub: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 36,
  },
  authBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.accent,
    borderRadius: 16,
    paddingVertical: 17,
    paddingHorizontal: 20,
  },
  authBtnPressed: {
    opacity: 0.85,
  },
  authBtnGIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  authBtnG: {
    color: T.white,
    fontSize: 14,
    fontWeight: "800",
  },
  authBtnLabel: {
    color: T.white,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  authFooter: {
    alignItems: "center",
    paddingBottom: 36,
    gap: 8,
  },
  authFooterLinks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authFooterLink: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterDivider: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterCopy: {
    color: "rgba(244,242,238,0.15)",
    fontSize: 11,
    letterSpacing: 3,
  },
  card: {
    gap: 18,
  },
  cardStepRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardStepText: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
  },
  cardTitle: {
    color: T.textPrimary,
    fontSize: 40,
    lineHeight: 46,
    fontWeight: "300",
    letterSpacing: -1.8,
  },
  cardBody: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  avatarTile: {
    width: "47%",
    minHeight: 132,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 18,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 14,
  },
  avatarTileActive: {
    borderColor: T.borderAccent,
    backgroundColor: "rgba(124,108,245,0.12)",
  },
  avatarGlyph: {
    color: T.textSecondary,
    fontSize: 32,
    lineHeight: 38,
  },
  avatarGlyphActive: {
    color: T.textPrimary,
  },
  avatarTileLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  avatarTileLabelActive: {
    color: T.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radiusSm,
    backgroundColor: T.surfaceCard,
    color: T.textPrimary,
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontSize: 16,
  },
  multilineInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radius,
    padding: 16,
    gap: 16,
    backgroundColor: T.surfaceCard,
  },
  toggleTextWrap: {
    gap: 2,
    flex: 1,
  },
  toggleLabel: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "500",
  },
  toggleSub: {
    color: T.textSecondary,
    fontSize: 13,
  },
  fieldBlock: {
    gap: 10,
  },
  fieldLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  infoBlock: {
    gap: 6,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  infoText: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  icebreakerText: {
    color: T.accentBright,
    fontStyle: "italic",
  },
  venuePage: {
    gap: 16,
  },
  venueHeader: {
    gap: 10,
  },
  venueName: {
    color: T.textPrimary,
    fontSize: 32,
    fontWeight: "300",
    letterSpacing: -1.2,
  },
  venueMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  venuePulse: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  venueActions: {
    marginTop: 8,
  },
  vibeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  venueChoiceList: {
    gap: 10,
  },
  pulseDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  pulseDotActive: {
    backgroundColor: T.teal,
  },
  visibleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  visibleBadgeLabel: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  energyPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  energyPillHigh: {
    borderColor: "rgba(62,207,178,0.3)",
    backgroundColor: T.tealDim,
  },
  energyPillLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  energyPillLabelHigh: {
    color: T.teal,
  },
  feedHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  feedHeadVenue: {
    color: T.textPrimary,
    fontSize: 24,
    fontWeight: "300",
    letterSpacing: -0.8,
  },
  feedHeadCount: {
    color: T.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  feedCard: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radius,
    padding: 16,
    gap: 12,
    marginBottom: 12,
    backgroundColor: T.surfaceCard,
  },
  feedCardPressed: {
    backgroundColor: "rgba(124,108,245,0.05)",
    borderColor: T.borderAccent,
  },
  feedCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedAvatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  feedAvatarGlyph: {
    color: T.accentBright,
    fontSize: 16,
    fontWeight: "600",
  },
  feedCardInfo: {
    flex: 1,
    gap: 2,
  },
  feedCardName: {
    color: T.textPrimary,
    fontSize: 17,
    fontWeight: "500",
  },
  feedCardIntent: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
  },
  feedCardTime: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  feedCardHint: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  feedCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 80,
    gap: 12,
  },
  emptyGlyph: {
    color: T.textMuted,
    fontSize: 48,
    fontWeight: "200",
  },
  emptyText: {
    color: T.textMuted,
    fontSize: 15,
  },
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  profileHeroBlock: {
    alignItems: "center",
    gap: 8,
    marginBottom: 24,
  },
  profileAvatarLg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  profileAvatarGlyph: {
    color: T.accentBright,
    fontSize: 30,
    fontWeight: "500",
  },
  profileName: {
    color: T.textPrimary,
    fontSize: 30,
    fontWeight: "300",
    letterSpacing: -1,
  },
  profileIntent: {
    color: T.textSecondary,
    fontSize: 14,
    textTransform: "capitalize",
  },
  chipWrapCenter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  profileSections: {
    gap: 0,
    marginBottom: 24,
  },
  profileActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  profileDestructive: {},
  settingsPage: {
    gap: 18,
  },
  settingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 8,
  },
  settingsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsAvatarGlyph: {
    color: T.accentBright,
    fontSize: 28,
    fontWeight: "600",
  },
  settingsIdentity: {
    flex: 1,
    gap: 4,
  },
  settingsTitle: {
    color: T.textPrimary,
    fontSize: 28,
    fontWeight: "300",
    letterSpacing: -0.8,
  },
  settingsSubtitle: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsActionStack: {
    gap: 10,
  },
  settingsInfoCard: {
    gap: 8,
    padding: 16,
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
  },
  settingsInfoTitle: {
    color: T.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  settingsInfoBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsSuccessText: {
    color: T.teal,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsDangerStack: {
    gap: 10,
    marginTop: 4,
  },
  adminPage: {
    gap: 18,
  },
  adminHeader: {
    gap: 12,
  },
  adminSubmissionList: {
    gap: 10,
  },
  adminDetailGrid: {
    gap: 16,
  },
  adminCandidateCard: {
    gap: 8,
    padding: 14,
    borderRadius: T.radiusSm,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceCard,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    letterSpacing: -1.5,
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
  safetyStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  safetyStatusText: {
    color: T.textSecondary,
    fontSize: 14,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: T.tealDim,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(62,207,178,0.2)",
  },
  chipSubtle: {
    backgroundColor: T.surfaceCard,
    borderColor: T.border,
  },
  chipLabel: {
    color: T.teal,
    fontSize: 12,
    fontWeight: "600",
  },
  chipLabelSubtle: {
    color: T.textSecondary,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  selectChip: {
    borderRadius: T.radiusSm,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "transparent",
  },
  selectChipActive: {
    borderColor: T.accent,
    backgroundColor: T.accentDim,
  },
  selectChipLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  selectChipLabelActive: {
    color: T.accentBright,
    fontWeight: "600",
  },
  primaryBtn: {
    backgroundColor: T.accent,
    borderRadius: T.radius,
    paddingVertical: 17,
    paddingHorizontal: 20,
    alignItems: "center",
    flex: 1,
  },
  primaryBtnPressed: {
    opacity: 0.85,
  },
  primaryBtnLabel: {
    color: T.white,
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  ghostBtn: {
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.border,
    paddingVertical: 17,
    paddingHorizontal: 20,
    alignItems: "center",
    flex: 1,
  },
  ghostBtnCompact: {
    flex: 0,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  ghostBtnDestructive: {
    borderColor: "rgba(255,80,80,0.25)",
  },
  ghostBtnLabel: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "500",
  },
  ghostBtnLabelDestructive: {
    color: "rgba(255,100,100,0.8)",
  },
  backNavButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingRight: 12,
  },
  backNavButtonPressed: {
    opacity: 0.8,
  },
  backNavIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(124,108,245,0.12)",
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  backNavIcon: {
    color: T.accentBright,
    fontSize: 24,
    lineHeight: 24,
    marginTop: -2,
  },
  backNavLabel: {
    color: T.textPrimary,
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  footerShell: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 26,
    backgroundColor: "rgba(22,20,30,0.94)",
    borderTopWidth: 1,
    borderTopColor: "rgba(71,69,84,0.38)",
  },
  footerSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  footerVenueBlock: {
    flex: 1,
    gap: 3,
  },
  footerVenueLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  footerVenueName: {
    color: T.teal,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  footerSessionMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(139,128,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(139,128,255,0.18)",
    maxWidth: "58%",
  },
  footerPresenceDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  footerPresenceDotActive: {
    backgroundColor: T.teal,
  },
  footerSessionText: {
    color: T.textPrimary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  footerNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  footerNavItem: {
    flex: 1,
    minHeight: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  footerNavItemActive: {
    backgroundColor: T.accent,
  },
  footerNavItemPressed: {
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  footerNavIcon: {
    color: T.textMuted,
    fontSize: 18,
    lineHeight: 20,
  },
  footerNavIconActive: {
    color: "#21008e",
  },
  footerNavLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  footerNavLabelActive: {
    color: "#21008e",
  },
  errorText: {
    color: "#ff8080",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
});
