import { StyleSheet } from "react-native";

export const T = {
  ink: "#fcfaff",
  inkSoft: "#ffffff",
  inkMid: "#e9e1ff",
  surface: "#ffffff",
  surfaceGlass: "rgba(255,255,255,0.54)",
  surfaceGlassStrong: "rgba(255,255,255,0.68)",
  surfaceGlassSoft: "rgba(248,244,255,0.46)",
  surfaceGlassUltra: "rgba(255,255,255,0.34)",
  surfaceGlassLilac: "rgba(248,244,255,0.30)",
  surfaceDim: "#f6f1ff",
  surfaceMid: "rgba(123,97,255,0.08)",
  surfaceCard: "#f8f4ff",
  accent: "#7b61ff",
  accentDim: "rgba(123,97,255,0.14)",
  accentBright: "#5f43ff",
  teal: "#7b61ff",
  tealDim: "rgba(123,97,255,0.1)",
  white: "#ffffff",
  textPrimary: "#171221",
  textSecondary: "rgba(23,18,33,0.7)",
  textMuted: "rgba(23,18,33,0.42)",
  borderBlack: "rgba(0,0,0,0.78)",
  borderBlackSoft: "rgba(0,0,0,0.58)",
  border: "rgba(123,97,255,0.14)",
  borderAccent: "rgba(123,97,255,0.34)",
  fontBody: "DMSans_400Regular",
  fontBodyMedium: "DMSans_500Medium",
  fontBodyBold: "DMSans_700Bold",
  fontDisplay: "Outfit_500Medium",
  fontDisplayBold: "Outfit_700Bold",
  fontDisplayLight: "Outfit_300Light",
  radius: 20,
  radiusSm: 12,
  radiusXl: 28,
};

export const styles = StyleSheet.create({
  absoluteFill: StyleSheet.absoluteFillObject,
  shell: {
    flex: 1,
    backgroundColor: T.ink,
  },
  grain: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.02,
    backgroundColor: "transparent",
  },
  waveLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  waveTrack: {
    position: "absolute",
    left: -240,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  waveSegmentClip: {
    width: 180,
    height: 52,
    overflow: "hidden",
    marginLeft: -2,
  },
  waveSegment: {
    width: 180,
    height: 104,
    borderRadius: 52,
    borderWidth: 1.5,
    borderColor: "rgba(0,0,0,0.84)",
    backgroundColor: "transparent",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 72,
    gap: 0,
  },
  contentWithFooter: {
    paddingBottom: 230,
  },
  fullContent: {
    flex: 1,
    padding: 0,
  },
  loadingWrap: {
    flex: 1,
    minHeight: 700,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  loadingCenter: {
    alignItems: "center",
    gap: 16,
  },
  loadingLogo: {
    width: 118,
    height: 28,
  },
  loadingRing: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingChevron: {
    color: T.accent,
    fontSize: 44,
    fontWeight: "200",
    lineHeight: 52,
    marginRight: -6,
  },
  loadingDot: {
    position: "absolute",
    right: 28,
    top: 38,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: T.accent,
  },
  loadingWordmark: {
    color: T.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 5,
  },
  loadingCaption: {
    color: T.textMuted,
    fontSize: 14,
  },
  authWrap: {
    flex: 1,
    minHeight: 812,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  authGlowTop: {
    position: "absolute",
    top: -120,
    left: "15%",
    right: "15%",
    height: 400,
    borderRadius: 200,
    backgroundColor: "rgba(123,97,255,0.16)",
  },
  authGlowBottom: {
    position: "absolute",
    bottom: -80,
    left: "10%",
    right: "10%",
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(123,97,255,0.08)",
  },
  authBrand: {
    alignItems: "center",
    paddingTop: 100,
    gap: 12,
  },
  authMarkRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: "rgba(123,97,255,0.24)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(123,97,255,0.1)",
  },
  authMarkChevron: {
    color: T.accentBright,
    fontSize: 34,
    fontWeight: "200",
    lineHeight: 40,
    marginRight: -4,
  },
  authMarkDot: {
    position: "absolute",
    right: 17,
    top: 24,
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: T.accent,
  },
  authWordmarkWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authWordmarkRule: {
    width: 26,
    height: 1,
    backgroundColor: "rgba(123,97,255,0.28)",
  },
  authWordmark: {
    color: T.accentBright,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 4.2,
  },
  authCard: {
    marginHorizontal: 20,
    borderRadius: T.radiusXl,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surface,
    paddingHorizontal: 26,
    paddingTop: 32,
    paddingBottom: 36,
    overflow: "hidden",
  },
  authCardAccentLine: {
    position: "absolute",
    top: 0,
    left: 40,
    right: 40,
    height: 1,
    backgroundColor: T.accent,
    opacity: 0.6,
  },
  authHeadline: {
    color: T.textPrimary,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "300",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    marginBottom: 14,
    textAlign: "center",
  },
  authSub: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 36,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  authBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: T.accent,
    borderRadius: 16,
    paddingVertical: 17,
    paddingHorizontal: 20,
  },
  authBtnPressed: {
    opacity: 0.85,
  },
  authBtnGIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  authBtnG: {
    color: T.white,
    fontSize: 14,
    fontWeight: "800",
  },
  authBtnLabel: {
    color: T.white,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  authFooter: {
    alignItems: "center",
    paddingBottom: 36,
    gap: 8,
  },
  authFooterLinks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  authFooterLink: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterDivider: {
    color: T.textMuted,
    fontSize: 13,
  },
  authFooterCopy: {
    color: "rgba(23,18,33,0.18)",
    fontSize: 11,
    letterSpacing: 3,
  },
  card: {
    gap: 18,
  },
  cardStepRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardStepText: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: T.fontBodyBold,
    letterSpacing: 2,
  },
  cardTitle: {
    color: T.textPrimary,
    fontSize: 40,
    lineHeight: 46,
    fontWeight: "300",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.8,
    textAlign: "center",
  },
  cardBody: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    fontFamily: T.fontBody,
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  avatarTile: {
    width: "47%",
    minHeight: 132,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 18,
    backgroundColor: T.surfaceCard,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 14,
  },
  avatarTileActive: {
    borderColor: T.borderAccent,
    backgroundColor: "rgba(123,97,255,0.12)",
  },
  avatarGlyph: {
    color: T.textSecondary,
    fontSize: 32,
    lineHeight: 38,
  },
  avatarGlyphActive: {
    color: T.textPrimary,
  },
  avatarTileLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  avatarTileLabelActive: {
    color: T.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radiusSm,
    backgroundColor: T.surfaceCard,
    color: T.textPrimary,
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontSize: 16,
  },
  multilineInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: T.radius,
    padding: 16,
    gap: 16,
    backgroundColor: T.surfaceCard,
  },
  toggleTextWrap: {
    gap: 2,
    flex: 1,
  },
  toggleLabel: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "500",
  },
  toggleSub: {
    color: T.textSecondary,
    fontSize: 13,
  },
  fieldBlock: {
    gap: 10,
  },
  fieldLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    fontFamily: T.fontBodyBold,
    letterSpacing: 2,
  },
  infoBlock: {
    gap: 6,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  infoText: {
    color: T.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: T.fontBody,
  },
  icebreakerText: {
    color: T.accentBright,
    fontStyle: "italic",
  },
  venuePage: {
    gap: 18,
  },
  venueHeroCard: {
    borderRadius: 34,
    borderWidth: 1,
    borderColor: T.borderBlack,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 22,
    overflow: "hidden",
    backgroundColor: T.surfaceGlassUltra,
    shadowColor: "#7b61ff",
    shadowOpacity: 0.12,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  venueHeroCardRadar: {
    borderRadius: 34,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 22,
    overflow: "hidden",
    backgroundColor: "#16121c",
    shadowColor: "#ff9cd7",
    shadowOpacity: 0.18,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  venueHeroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 18,
  },
  venueHeroEyebrow: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2.4,
    textTransform: "uppercase",
  },
  venueHeroEyebrowRadar: {
    color: "rgba(255,255,255,0.48)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2.4,
    textTransform: "uppercase",
  },
  venueStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueStatusPillRadar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  venueStatusDotActive: {
    backgroundColor: T.accent,
  },
  venueStatusDotRadar: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  venueStatusDotRadarActive: {
    backgroundColor: "#7dff8a",
  },
  venueStatusLabel: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  venueStatusLabelRadar: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 12,
    fontWeight: "700",
  },
  venueHeaderRow: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  venueRadarHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
  },
  venueHeaderCopy: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minWidth: 0,
    gap: 6,
    alignItems: "center",
  },
  venueHeaderCopyRadar: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  venueName: {
    color: T.accentBright,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
    textAlign: "center",
  },
  venueNameRadar: {
    color: T.white,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700",
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
  },
  venueVisibleCount: {
    color: T.textSecondary,
    fontSize: 15,
    fontWeight: "500",
    fontFamily: T.fontBodyMedium,
    textAlign: "center",
  },
  venueVisibleCountRadar: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 15,
    fontWeight: "500",
    fontFamily: T.fontBodyMedium,
  },
  venuePulseCopy: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 260,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  venuePulseCopyRadar: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 260,
    fontFamily: T.fontBody,
  },
  venueEnergyPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    flexShrink: 0,
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.accentDim,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  venueHeaderMetaStack: {
    alignItems: "flex-end",
    gap: 10,
  },
  venueEnergyPillRadar: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,170,222,0.34)",
    backgroundColor: "rgba(255,170,222,0.12)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  venueEnergyIcon: {
    color: T.accentBright,
    fontSize: 14,
    fontWeight: "800",
  },
  venueEnergyIconRadar: {
    color: "#ff9bd9",
    fontSize: 14,
    fontWeight: "800",
  },
  venueEnergyLabel: {
    color: T.accentBright,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.2,
  },
  venueEnergyLabelRadar: {
    color: "#ffd5ef",
    fontSize: 12,
    fontWeight: "800",
    fontFamily: T.fontBodyBold,
    letterSpacing: 1.2,
  },
  venueIntentBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  venueIntentBadgeLabel: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 12,
    fontWeight: "700",
  },
  venueStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  venueStatCard: {
    flex: 1,
    minHeight: 78,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassLilac,
    paddingHorizontal: 14,
    paddingVertical: 14,
    justifyContent: "space-between",
    gap: 10,
  },
  venueStatValue: {
    color: T.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    letterSpacing: -0.4,
  },
  venueStatLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  venueSignalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 22,
  },
  venueSignalCard: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  venueSignalAvatarWrap: {
    position: "relative",
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
  },
  venueSignalAvatarRing: {
    width: 74,
    height: 74,
    borderRadius: 37,
    padding: 3,
  },
  venueSignalAvatarInner: {
    flex: 1,
    borderRadius: 34,
    backgroundColor: "rgba(22,18,28,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueSignalAvatarGlyph: {
    color: T.white,
    fontSize: 24,
    fontWeight: "700",
  },
  venueSignalOnlineDot: {
    position: "absolute",
    right: 3,
    bottom: 6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#7dff8a",
    borderWidth: 2,
    borderColor: "#16121c",
  },
  venueSignalName: {
    color: T.white,
    fontSize: 13,
    fontWeight: "600",
    maxWidth: 78,
    textAlign: "center",
  },
  venueRadarStage: {
    height: 620,
    marginTop: 22,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  venueRadarStagePrivate: {
    height: 500,
  },
  venueRadarGlow: {
    position: "absolute",
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: "rgba(255,165,221,0.08)",
    shadowColor: "#ff9cd7",
    shadowOpacity: 0.68,
    shadowRadius: 76,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarAuraOuter: {
    position: "absolute",
    width: 402,
    height: 402,
    borderRadius: 201,
    borderWidth: 18,
    borderColor: "rgba(255,176,228,0.12)",
  },
  venueRadarAuraInner: {
    position: "absolute",
    width: 298,
    height: 298,
    borderRadius: 149,
    borderWidth: 10,
    borderColor: "rgba(255,176,228,0.09)",
  },
  venueRadarRingOuter: {
    position: "absolute",
    width: 368,
    height: 368,
    borderRadius: 184,
    borderWidth: 4,
    borderColor: "rgba(255,176,228,0.74)",
    shadowColor: "#ff9cd7",
    shadowOpacity: 0.42,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarRingMid: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 4,
    borderColor: "rgba(255,176,228,0.54)",
  },
  venueRadarRingInner: {
    position: "absolute",
    width: 196,
    height: 196,
    borderRadius: 98,
    borderWidth: 3,
    borderColor: "rgba(255,176,228,0.26)",
  },
  venueRadarPing: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarPingRing: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    padding: 3,
    shadowColor: "#ff9cd7",
    shadowOpacity: 0.34,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  venueRadarPingInner: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: "rgba(20,17,26,0.96)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarPingGlyph: {
    color: T.white,
    fontSize: 22,
    fontWeight: "700",
  },
  venueRadarPingPresence: {
    position: "absolute",
    right: 2,
    bottom: 4,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#7dff8a",
    borderWidth: 2,
    borderColor: "#16121c",
  },
  venueRadarPingLabelWrap: {
    position: "absolute",
    bottom: -18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  venueRadarPingLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    fontWeight: "700",
  },
  venueRadarCountBadge: {
    position: "absolute",
    top: 78,
    left: 68,
    minWidth: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarCountBadgeLabel: {
    color: T.white,
    fontSize: 18,
    fontWeight: "800",
  },
  venueRadarCenterWrap: {
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  venueRadarCenterRing: {
    width: 142,
    height: 142,
    borderRadius: 71,
    padding: 4,
    shadowColor: "#ff9cd7",
    shadowOpacity: 0.5,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 0 },
  },
  venueRadarCenterCore: {
    flex: 1,
    borderRadius: 67,
    backgroundColor: "rgba(31,24,39,0.96)",
    alignItems: "center",
    justifyContent: "center",
  },
  venueRadarCenterGlyph: {
    color: T.white,
    fontSize: 52,
    fontFamily: T.fontDisplayBold,
  },
  venueRadarCenterLabel: {
    color: T.white,
    fontSize: 26,
    fontFamily: T.fontDisplayBold,
    letterSpacing: -0.4,
  },
  venueRadarCenterCaption: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 14,
    textAlign: "center",
    maxWidth: 220,
    lineHeight: 21,
  },
  venueRadarEmptyCard: {
    position: "absolute",
    bottom: 82,
    width: 256,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 8,
  },
  venueRadarEmptyTitle: {
    color: T.white,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  venueRadarEmptyBody: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  venueClusterArea: {
    height: 520,
    justifyContent: "flex-end",
    paddingBottom: 118,
    position: "relative",
  },
  venueClusterAreaPrivate: {
    height: 360,
    paddingBottom: 64,
  },
  venueClusterGlow: {
    position: "absolute",
    top: 154,
    left: 118,
    width: 138,
    height: 138,
    borderRadius: 69,
    backgroundColor: "rgba(123,97,255,0.14)",
    shadowColor: "#7b61ff",
    shadowOpacity: 0.6,
    shadowRadius: 44,
    shadowOffset: { width: 0, height: 0 },
  },
  venueBubble: {
    position: "absolute",
    borderWidth: 1,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  venueBubbleStandard: {
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
  },
  venueBubbleFeatured: {
    borderColor: T.accent,
    borderWidth: 6,
    backgroundColor: "#f1ebff",
    shadowOpacity: 0.55,
    shadowRadius: 28,
  },
  venueBubblePressed: {
    transform: [{ scale: 0.97 }],
  },
  venueBubbleInner: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  venueBubbleGlyph: {
    color: T.accentBright,
    fontSize: 26,
    fontWeight: "700",
  },
  venueBubbleGlyphFeatured: {
    color: T.textPrimary,
    fontSize: 36,
  },
  venueCountBubble: {
    position: "absolute",
    top: 74,
    left: 66,
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassUltra,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7b61ff",
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  venueCountBubbleLabel: {
    color: T.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  venueClusterHint: {
    alignSelf: "center",
    color: T.textMuted,
    textTransform: "uppercase",
    fontSize: 13,
    letterSpacing: 3.2,
  },
  venueEmptyClusterCard: {
    marginTop: 132,
    marginHorizontal: 18,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassUltra,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 8,
    shadowColor: "#7b61ff",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  venueEmptyClusterTitle: {
    color: T.textPrimary,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  venueEmptyClusterBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  venueVibesSection: {
    gap: 16,
  },
  venueSectionLabel: {
    color: T.textPrimary,
    fontSize: 18,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
  },
  venueSectionLabelRadar: {
    color: T.white,
    fontSize: 18,
    fontWeight: "500",
    fontFamily: T.fontDisplay,
  },
  venueVibesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  venueVibePill: {
    minWidth: 166,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  venueVibePillPrimary: {
    borderColor: T.borderAccent,
    backgroundColor: "rgba(123,97,255,0.12)",
  },
  venueVibePillSecondary: {
    borderColor: T.border,
    backgroundColor: T.surfaceGlassUltra,
  },
  venueVibePillMuted: {
    minWidth: 166,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: "rgba(246,241,255,0.52)",
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  venueVibeDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  venueVibeDotPrimary: {
    backgroundColor: T.accent,
  },
  venueVibeDotSecondary: {
    backgroundColor: T.accentBright,
  },
  venueVibeText: {
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: -0.3,
  },
  venueVibeTextPrimary: {
    color: T.accentBright,
  },
  venueVibeTextSecondary: {
    color: T.textPrimary,
  },
  venueVibeTextMuted: {
    color: T.textMuted,
    fontSize: 16,
    fontWeight: "500",
  },
  venuePreviewSection: {
    marginTop: 24,
    gap: 14,
  },
  venuePreviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  venuePreviewLink: {
    color: "#ffc2e8",
    fontSize: 13,
    fontWeight: "700",
  },
  venuePreviewList: {
    gap: 10,
  },
  venuePreviewCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  venuePreviewCardPressed: {
    borderColor: "rgba(255,176,228,0.4)",
    backgroundColor: "rgba(255,176,228,0.12)",
  },
  venuePreviewAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,176,228,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,176,228,0.34)",
    alignItems: "center",
    justifyContent: "center",
  },
  venuePreviewAvatarGlyph: {
    color: T.white,
    fontSize: 16,
    fontWeight: "700",
  },
  venuePreviewCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  venuePreviewName: {
    color: T.white,
    fontSize: 15,
    fontWeight: "600",
  },
  venuePreviewMeta: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 13,
  },
  venuePreviewTime: {
    color: "rgba(255,255,255,0.44)",
    fontSize: 12,
    fontWeight: "700",
  },
  momentumCard: {
    marginTop: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.06)",
    padding: 18,
    gap: 10,
  },
  momentumHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  momentumEyebrow: {
    color: "#ffc2e8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  momentumDismiss: {
    color: "rgba(255,255,255,0.46)",
    fontSize: 12,
    fontWeight: "700",
  },
  momentumTitle: {
    color: T.white,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "600",
    letterSpacing: -0.4,
  },
  momentumBody: {
    color: "rgba(255,255,255,0.66)",
    fontSize: 14,
    lineHeight: 21,
  },
  momentumActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  momentumPrimaryButton: {
    borderRadius: 999,
    backgroundColor: "#ff8fd9",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  momentumPrimaryLabel: {
    color: "#24182d",
    fontSize: 13,
    fontWeight: "700",
  },
  momentumGhostButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  momentumGhostLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 13,
    fontWeight: "700",
  },
  venueActions: {
    marginTop: 26,
  },
  venueChoiceList: {
    gap: 10,
  },
  pulseDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  pulseDotActive: {
    backgroundColor: T.teal,
  },
  visibleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  visibleBadgeLabel: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  energyPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  energyPillHigh: {
    borderColor: "rgba(62,207,178,0.3)",
    backgroundColor: T.tealDim,
  },
  energyPillLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  energyPillLabelHigh: {
    color: T.teal,
  },
  feedHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  feedHeadVenue: {
    color: T.textPrimary,
    fontSize: 24,
    fontWeight: "300",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.8,
    textAlign: "center",
  },
  feedHeadCount: {
    color: T.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  feedCard: {
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    borderRadius: T.radius,
    padding: 16,
    gap: 12,
    marginBottom: 12,
    backgroundColor: T.surfaceGlassLilac,
  },
  feedCardPressed: {
    backgroundColor: T.accentDim,
    borderColor: T.borderAccent,
  },
  feedCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  feedAvatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  feedAvatarGlyph: {
    color: T.accentBright,
    fontSize: 16,
    fontWeight: "600",
  },
  feedCardInfo: {
    flex: 1,
    gap: 2,
  },
  feedCardName: {
    color: T.textPrimary,
    fontSize: 17,
    fontWeight: "500",
  },
  feedCardIntent: {
    color: T.textSecondary,
    fontSize: 13,
    textTransform: "capitalize",
  },
  feedCardTime: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  feedCardHint: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  feedCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 80,
    gap: 12,
  },
  emptyGlyph: {
    color: T.textMuted,
    fontSize: 48,
    fontWeight: "200",
  },
  emptyText: {
    color: T.textMuted,
    fontSize: 15,
  },
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  profileHeroBlock: {
    alignItems: "center",
    gap: 8,
    marginBottom: 24,
  },
  profileAvatarLg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  profileAvatarGlyph: {
    color: T.accentBright,
    fontSize: 30,
    fontWeight: "500",
  },
  profileName: {
    color: T.textPrimary,
    fontSize: 30,
    fontWeight: "300",
    fontFamily: T.fontDisplay,
    letterSpacing: -1,
    textAlign: "center",
  },
  profileIntent: {
    color: T.textSecondary,
    fontSize: 14,
    textTransform: "capitalize",
  },
  chipWrapCenter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  profileSections: {
    gap: 0,
    marginBottom: 24,
  },
  profileActions: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  profileDestructive: {
    gap: 10,
    marginBottom: 18,
  },
  reportPanel: {
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,100,100,0.18)",
    borderRadius: T.radius,
    backgroundColor: "rgba(255,80,80,0.04)",
    padding: 14,
  },
  reportPanelTitle: {
    color: T.textPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  reportChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  settingsPage: {
    gap: 18,
  },
  settingsHeader: {
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    marginBottom: 8,
  },
  settingsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsAvatarGlyph: {
    color: T.accentBright,
    fontSize: 28,
    fontWeight: "600",
  },
  settingsIdentity: {
    gap: 4,
    alignItems: "center",
  },
  settingsTitle: {
    color: T.textPrimary,
    fontSize: 28,
    fontWeight: "300",
    fontFamily: T.fontDisplay,
    letterSpacing: -0.8,
    textAlign: "center",
  },
  settingsSubtitle: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: T.fontBody,
    textAlign: "center",
  },
  settingsActionStack: {
    gap: 10,
  },
  settingsInfoCard: {
    gap: 8,
    padding: 16,
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
  },
  settingsInfoTitle: {
    color: T.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  settingsInfoBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsSuccessText: {
    color: T.accentBright,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsDangerStack: {
    gap: 10,
    marginTop: 4,
  },
  adminPage: {
    gap: 18,
  },
  adminHeader: {
    gap: 12,
  },
  adminSubmissionList: {
    gap: 10,
  },
  adminDetailGrid: {
    gap: 16,
  },
  adminCandidateCard: {
    gap: 8,
    padding: 14,
    borderRadius: T.radiusSm,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceCard,
  },
  approachHero: {
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
    paddingTop: 8,
  },
  approachLabel: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  approachName: {
    color: T.accent,
    fontSize: 42,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  timerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 2,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 0,
  },
  timerNum: {
    color: T.textPrimary,
    fontSize: 44,
    fontWeight: "200",
    fontFamily: T.fontDisplayLight,
    letterSpacing: -2,
    lineHeight: 50,
  },
  timerUnit: {
    color: T.textMuted,
    fontSize: 12,
    letterSpacing: 1,
  },
  approachSections: {
    gap: 0,
    marginBottom: 24,
  },
  feedbackPromptOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(123,97,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 30,
  },
  feedbackPromptCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: T.borderBlack,
    backgroundColor: T.surface,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 18,
    gap: 16,
  },
  feedbackPromptEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  feedbackPromptTitle: {
    color: T.textPrimary,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "300",
    fontFamily: T.fontDisplay,
    letterSpacing: -1,
    textAlign: "center",
  },
  feedbackPromptBody: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  feedbackPromptBlock: {
    gap: 10,
  },
  feedbackPromptChoiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  feedbackPromptIcebreaker: {
    color: T.accentBright,
    fontSize: 14,
    lineHeight: 20,
    fontStyle: "italic",
  },
  feedbackPromptActions: {
    gap: 10,
  },
  feedbackPromptHint: {
    color: T.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  safetyStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  safetyStatusText: {
    color: T.textSecondary,
    fontSize: 14,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: T.tealDim,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: T.borderAccent,
  },
  chipSubtle: {
    backgroundColor: T.surfaceCard,
    borderColor: T.border,
  },
  chipLabel: {
    color: T.teal,
    fontSize: 12,
    fontWeight: "600",
  },
  chipLabelSubtle: {
    color: T.textSecondary,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  selectChip: {
    borderRadius: T.radiusSm,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "transparent",
  },
  selectChipActive: {
    borderColor: T.accent,
    backgroundColor: T.accentDim,
  },
  selectChipLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  selectChipLabelActive: {
    color: T.accentBright,
    fontWeight: "600",
  },
  primaryBtn: {
    backgroundColor: T.accent,
    borderRadius: T.radius,
    paddingVertical: 17,
    paddingHorizontal: 20,
    alignItems: "center",
    flex: 1,
  },
  primaryBtnPressed: {
    opacity: 0.85,
  },
  primaryBtnLabel: {
    color: T.white,
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  ghostBtn: {
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    paddingVertical: 17,
    paddingHorizontal: 20,
    alignItems: "center",
    flex: 1,
  },
  ghostBtnCompact: {
    flex: 0,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  ghostBtnDestructive: {
    borderColor: "rgba(255,80,80,0.25)",
  },
  ghostBtnLabel: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "500",
  },
  ghostBtnLabelDestructive: {
    color: "rgba(255,100,100,0.8)",
  },
  backNavButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingRight: 12,
    paddingVertical: 4,
  },
  backNavButtonPressed: {
    opacity: 0.8,
  },
  backNavIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  backNavIcon: {
    color: T.accent,
    fontSize: 22,
    fontWeight: "200",
    lineHeight: 26,
    marginRight: -3,
  },
  backNavDot: {
    position: "absolute",
    right: 10,
    top: 14,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: T.accent,
  },
  backNavLabel: {
    color: T.textSecondary,
    fontSize: 14,
    fontWeight: "600",
  },
  footerShell: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  footerSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: T.surface,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
  },
  footerPrivateRow: {
    marginBottom: 10,
    alignItems: "center",
  },
  footerPrivateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.borderBlackSoft,
    backgroundColor: T.surfaceGlassStrong,
  },
  footerPrivateDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.accent,
  },
  footerPrivateText: {
    color: T.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  footerVenueBlock: {
    flex: 1,
    gap: 3,
  },
  footerVenueLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  footerVenueName: {
    color: T.accentBright,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  footerSessionMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.borderAccent,
    maxWidth: "58%",
  },
  footerPresenceDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.textMuted,
  },
  footerPresenceDotActive: {
    backgroundColor: T.teal,
  },
  footerSessionText: {
    color: T.textPrimary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  footerNavRow: {
    position: "relative",
    minHeight: 76,
    marginTop: 2,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 2,
    backgroundColor: T.surface,
    borderWidth: 1,
    borderColor: T.borderBlack,
    overflow: "visible",
  },
  footerNavTrack: {
    position: "relative",
    alignSelf: "center",
    width: "86%",
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
  },
  footerNavBubbleTrack: {
    position: "absolute",
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "flex-start",
    zIndex: 0,
  },
  footerNavMound: {
    position: "absolute",
    top: -16,
    width: 76,
    height: 28,
    borderTopLeftRadius: 38,
    borderTopRightRadius: 38,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: T.surface,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: T.borderBlack,
  },
  footerNavItem: {
    flex: 1,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  footerNavItemActive: {
    zIndex: 2,
  },
  footerNavItemPressed: {
    opacity: 0.86,
  },
  footerNavIconBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNavIconPlaceholder: {
    width: 40,
    height: 40,
  },
  footerNavIconBubbleActive: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: T.accent,
    shadowColor: "#7b61ff",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    marginTop: -6,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNavIcon: {
    color: T.textMuted,
    fontSize: 22,
    lineHeight: 24,
  },
  footerNavIconActive: {
    color: "#21008e",
  },
  footerNavLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  footerNavLabelActive: {
    color: "#21008e",
  },
  errorText: {
    color: "#ff8080",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
});
