import { T } from "../theme";

export function createNavigationStyles(contentRailWidth: "92%", contentRailMax: number) {
  return {
    backNavButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 0,
      paddingRight: 0,
      paddingVertical: 4,
    },
    backNavButtonPressed: {
      opacity: 0.8,
    },
    backNavIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: "rgba(255,251,245,0.92)",
      borderWidth: 1,
      borderColor: "rgba(53,102,77,0.14)",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#DCCCB3",
      shadowOpacity: 0.1,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    backNavLabel: {
      color: T.textSecondary,
      fontSize: 14,
      fontWeight: "600",
    },
    footerShell: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 20,
      paddingTop: 4,
      paddingBottom: 10,
      backgroundColor: "transparent",
      overflow: "visible",
    },
    footerSummaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      marginBottom: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: T.radius,
      backgroundColor: T.surface,
      borderWidth: 1,
      borderColor: T.borderBlackSoft,
    },
    footerPrivateRow: {
      marginBottom: 10,
      alignItems: "center",
    },
    footerPrivateBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: T.radiusLg,
      borderWidth: 1,
      borderColor: T.borderBlackSoft,
      backgroundColor: T.surfaceGlassStrong,
    },
    footerPrivateDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: T.visibilityOff,
    },
    footerPrivateText: {
      color: T.textSecondary,
      fontSize: 12,
      fontWeight: "600",
    },
    footerVenueBlock: {
      flex: 1,
      gap: 3,
    },
    footerVenueLabel: {
      color: T.textMuted,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 2,
    },
    footerVenueName: {
      color: T.accentBright,
      fontSize: 18,
      fontWeight: "700",
      letterSpacing: -0.4,
    },
    footerSessionMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: T.radiusLg,
      backgroundColor: T.accentDim,
      borderWidth: 1,
      borderColor: T.borderAccent,
      maxWidth: "58%",
    },
    footerPresenceDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: T.textMuted,
    },
    footerPresenceDotActive: {
      backgroundColor: T.visibilityOn,
    },
    footerSessionText: {
      color: T.textPrimary,
      fontSize: 12,
      fontWeight: "600",
      textTransform: "capitalize",
    },
    footerNavRow: {
      position: "relative",
      minHeight: 96,
      marginTop: 2,
      paddingHorizontal: 4,
      paddingTop: 8,
      paddingBottom: 4,
      overflow: "visible",
    },
    footerNavTrack: {
      position: "relative",
      alignSelf: "center",
      width: contentRailWidth,
      maxWidth: contentRailMax,
      minHeight: 80,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 8,
      borderRadius: 30,
      backgroundColor: "rgba(255,251,245,0.98)",
      borderWidth: 1,
      borderColor: "rgba(53,102,77,0.08)",
      shadowColor: "#000000",
      shadowOpacity: 0.12,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: -6 },
      elevation: 10,
    },
    footerNavBubbleTrack: {
      position: "absolute",
      top: -10,
      bottom: 0,
      alignItems: "center",
      justifyContent: "flex-start",
      zIndex: 0,
    },
    footerNavItem: {
      flex: 1,
      minHeight: 54,
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 5,
      zIndex: 1,
    },
    footerNavItemActive: {
      zIndex: 2,
      paddingTop: 10,
    },
    footerNavItemPressed: {
      opacity: 0.86,
    },
    footerNavIconBubble: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    footerNavIconPlaceholder: {
      width: 32,
      height: 32,
    },
    footerNavIconBubbleActive: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: T.accent,
      borderWidth: 2,
      borderColor: "rgba(255,250,242,0.98)",
      shadowColor: T.accent,
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
      marginTop: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    footerNavIcon: {
      color: T.textMuted,
      fontSize: 22,
      lineHeight: 24,
    },
    footerNavIconActive: {
      color: T.accentBright,
    },
    footerNavLabel: {
      color: "rgba(31,46,36,0.60)",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.1,
      width: "100%",
      textAlign: "center",
    },
    footerNavLabelActive: {
      color: T.primary,
      fontWeight: "800",
    },
  } as const;
}
