import { T } from "../theme";
import { leftShadows } from "../shadow";

export const uiStyles = {
  chip: {
    borderRadius: 999,
    backgroundColor: T.tealDim,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: T.borderAccent,
  },
  chipSubtle: {
    backgroundColor: T.surfaceCard,
    borderColor: T.border,
  },
  chipLabel: {
    color: T.teal,
    fontSize: 12,
    fontWeight: "600",
  },
  chipLabelSubtle: {
    color: T.textSecondary,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  selectChip: {
    borderRadius: T.radius,
    borderWidth: 1,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "transparent",
  },
  selectChipActive: {
    borderColor: T.accent,
    backgroundColor: T.accentDim,
  },
  selectChipLabel: {
    color: T.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  selectChipLabelActive: {
    color: T.accentBright,
    fontWeight: "600",
  },
  iconSelectChip: {
    position: "relative",
    minHeight: 52,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.borderAccent,
    backgroundColor: T.surfaceGlassStrong,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconSelectChipCompact: {
    minWidth: 88,
    flex: 1,
    justifyContent: "center",
  },
  iconSelectChipHalfWidth: {
    flexBasis: "47%",
    flexGrow: 1,
  },
  iconSelectChipActive: {
    borderColor: T.visibilityOff,
    backgroundColor: T.visibilityOffSoft,
  },
  iconSelectChipLabel: {
    color: T.textSecondary,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: T.fontBodyMedium,
  },
  iconSelectChipLabelCompact: {
    fontSize: 16,
    lineHeight: 18,
  },
  iconSelectChipLabelActive: {
    color: T.textPrimary,
    fontFamily: T.fontBodyBold,
  },
  iconSelectChipCheck: {
    position: "absolute",
    right: -6,
    top: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: T.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: T.white,
  },
  statusPillBase: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "#E2E8E1",
  },
  statusPillDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusPillDotVisible: {
    backgroundColor: "#2E7D32",
  },
  statusPillDotHidden: {
    backgroundColor: "#FFC24D",
  },
  statusPillLabel: {
    color: T.textPrimary,
    fontSize: 16,
    fontFamily: T.fontBodyMedium,
  },
  utilityIconButton: {
    minWidth: 74,
    height: 74,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.82)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,107,74,0.10)",
    gap: 6,
    paddingHorizontal: 10,
    ...leftShadows.medium,
  },
  utilityIconButtonCompact: {
    minWidth: 52,
    width: 52,
    height: 52,
    borderRadius: 18,
    paddingHorizontal: 0,
  },
  utilityIconButtonIconOnly: {
    gap: 0,
  },
  utilityIconButtonLabel: {
    color: T.textPrimary,
    fontSize: 13,
    fontFamily: T.fontBodyMedium,
  },
  venueIdentityBlock: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    minWidth: 0,
  },
  venueIdentityBlockIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: T.venueAccentSoft,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: T.venueAccent,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  venueIdentityBlockIconWrapHero: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  venueIdentityBlockCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  venueIdentityBlockTitle: {
    color: T.textPrimary,
    fontSize: 17,
    lineHeight: 20,
    fontFamily: T.fontDisplayBold,
  },
  venueIdentityBlockTitleHero: {
    fontSize: 24,
    lineHeight: 29,
    letterSpacing: -0.5,
  },
  venueIdentityBlockMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  venueIdentityBlockMetaText: {
    color: T.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: T.fontBodyMedium,
  },
  venueIdentityBlockMetaTextHero: {
    color: T.primary,
    fontSize: 15,
  },
  venueIdentityBlockSecondaryText: {
    color: T.textSecondary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: T.fontBody,
  },
} as const;
