import { alpha, leftColors, semanticColors } from "../color";
import { radii, typography } from "../token";

export const T = {
  ink: leftColors.porcelain,
  inkSoft: leftColors.white,
  inkMid: leftColors.porcelainMuted,
  primary: leftColors.moss,
  primarySoft: leftColors.mossSoft,
  secondary: leftColors.charcoal,
  secondarySoft: leftColors.porcelainMuted,
  tertiarySoft: leftColors.stone,
  surface: leftColors.porcelain,
  surfaceGlass: alpha(leftColors.white, 0.72),
  surfaceGlassStrong: alpha(leftColors.white, 0.88),
  surfaceGlassSoft: alpha(leftColors.white, 0.62),
  surfaceGlassUltra: alpha(leftColors.white, 0.78),
  surfaceGlassLilac: alpha(leftColors.charcoal, 0.06),
  surfaceDim: leftColors.porcelainSoft,
  surfaceMid: alpha(leftColors.inkBlack, 0.04),
  surfaceCard: leftColors.white,
  accent: leftColors.moss,
  accentDim: alpha(leftColors.moss, 0.12),
  accentBright: leftColors.moss,
  actionSurface: leftColors.actionBrown,
  actionContent: leftColors.white,
  actionContentSoft: alpha(leftColors.white, 0.18),
  visibilityOn: semanticColors.success,
  visibilityOnSoft: alpha(semanticColors.success, 0.14),
  visibilityOff: semanticColors.warning,
  visibilityOffSoft: alpha(semanticColors.warning, 0.14),
  warningBorder: alpha(semanticColors.warning, 0.3),
  venueAccent: leftColors.moss,
  venueAccentSoft: alpha(leftColors.moss, 0.14),
  venueSurface: alpha(leftColors.moss, 0.06),
  danger: semanticColors.error,
  dangerDim: alpha(semanticColors.error, 0.1),
  dangerBorder: alpha(semanticColors.error, 0.22),
  dangerText: semanticColors.error,
  onboardingInk: leftColors.creoleBrown,
  onboardingAccent: leftColors.moss,
  teal: semanticColors.info,
  tealDim: alpha(semanticColors.info, 0.16),
  white: leftColors.white,
  textPrimary: leftColors.inkBlack,
  textSecondary: alpha(leftColors.inkBlack, 0.68),
  textMuted: alpha(leftColors.inkBlack, 0.46),
  borderBlack: alpha(leftColors.inkBlack, 0.14),
  borderBlackSoft: alpha(leftColors.inkBlack, 0.08),
  border: alpha(leftColors.inkBlack, 0.08),
  borderAccent: alpha(leftColors.inkBlack, 0.16),
  onboardingInkSoft: alpha(leftColors.creoleBrown, 0.68),
  onboardingInkMuted: alpha(leftColors.creoleBrown, 0.46),
  onboardingBorder: alpha(leftColors.creoleBrown, 0.14),
  onboardingBorderStrong: alpha(leftColors.creoleBrown, 0.28),
  onboardingDecorativeBorder: alpha(leftColors.creoleBrown, 0.08),
  onboardingAccentSoft: alpha(leftColors.moss, 0.18),
  onboardingAccentFaint: alpha(leftColors.moss, 0.08),
  onboardingAccentMedium: alpha(leftColors.moss, 0.22),
  toastSurface: alpha(leftColors.actionBrown, 0.94),
  glassDark: alpha(leftColors.creoleBrown, 0.58),
  glassDarkSolid: alpha(leftColors.creoleBrown, 0.97),
  glassLight: alpha(leftColors.white, 0.56),
  glassLightMedium: alpha(leftColors.white, 0.68),
  glassLightSolid: alpha(leftColors.white, 0.96),
  glassLightReduced: alpha(leftColors.porcelain, 0.98),
  glassBorder: alpha(leftColors.white, 0.58),
  glassBorderStrong: alpha(leftColors.white, 0.65),
  glassBorderDark: alpha(leftColors.white, 0.22),
  navActiveSurface: alpha(leftColors.white, 0.14),
  navActiveBorder: alpha(leftColors.white, 0.26),
  navActiveContent: leftColors.white,
  navInactiveContent: alpha(leftColors.white, 0.66),
  fontBody: typography.fontBody,
  fontBodyMedium: typography.fontBodyMedium,
  fontBodyBold: typography.fontBodyBold,
  fontDisplay: typography.fontDisplay,
  fontDisplayBold: typography.fontDisplayBold,
  fontDisplayLight: typography.fontDisplayLight,
  radiusXs: radii.sm,
  radius: radii.lg,
  radiusSm: radii.md,
  radiusLg: radii.xl,
  radiusXl: radii.xxl,
} as const;
