import { alpha, leftColors, semanticColors } from "../color";
import { radii, typography } from "../token";

export const T = {
  ink: leftColors.porcelain,
  inkSoft: leftColors.white,
  inkMid: leftColors.porcelainMuted,
  primary: leftColors.inkBlack,
  primarySoft: leftColors.porcelainSoft,
  secondary: leftColors.charcoal,
  secondarySoft: leftColors.porcelainMuted,
  tertiarySoft: leftColors.stone,
  surface: leftColors.porcelain,
  surfaceGlass: alpha(leftColors.white, 0.72),
  surfaceGlassStrong: alpha(leftColors.white, 0.88),
  surfaceGlassSoft: alpha(leftColors.white, 0.62),
  surfaceGlassUltra: alpha(leftColors.white, 0.78),
  surfaceGlassLilac: alpha(leftColors.charcoal, 0.06),
  surfaceDim: leftColors.porcelainSoft,
  surfaceMid: alpha(leftColors.inkBlack, 0.04),
  surfaceCard: leftColors.white,
  accent: leftColors.inkBlack,
  accentDim: alpha(leftColors.inkBlack, 0.08),
  accentBright: leftColors.inkBlack,
  visibilityOn: semanticColors.success,
  visibilityOnSoft: alpha(semanticColors.success, 0.14),
  visibilityOff: semanticColors.warning,
  visibilityOffSoft: alpha(semanticColors.warning, 0.14),
  danger: semanticColors.error,
  dangerDim: alpha(semanticColors.error, 0.1),
  dangerBorder: alpha(semanticColors.error, 0.22),
  dangerText: semanticColors.error,
  teal: semanticColors.info,
  tealDim: alpha(semanticColors.info, 0.16),
  white: leftColors.white,
  textPrimary: leftColors.inkBlack,
  textSecondary: alpha(leftColors.inkBlack, 0.68),
  textMuted: alpha(leftColors.inkBlack, 0.46),
  borderBlack: alpha(leftColors.inkBlack, 0.14),
  borderBlackSoft: alpha(leftColors.inkBlack, 0.08),
  border: alpha(leftColors.inkBlack, 0.08),
  borderAccent: alpha(leftColors.inkBlack, 0.16),
  fontBody: typography.fontBody,
  fontBodyMedium: typography.fontBodyMedium,
  fontBodyBold: typography.fontBodyBold,
  fontDisplay: typography.fontDisplay,
  fontDisplayBold: typography.fontDisplayBold,
  fontDisplayLight: typography.fontDisplayLight,
  radiusXs: radii.sm,
  radius: radii.lg,
  radiusSm: radii.md,
  radiusLg: radii.xl,
  radiusXl: radii.xxl,
} as const;
